#region "copyright"

/*
    Copyright (c) 2026 Open Astro and the OpenAstro Ara contributors

    This file is part of OpenAstro Ara (forked from N.I.N.A.).

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
*/

#endregion "copyright"

using NUnit.Framework;
using OpenAstroAra.Server.Services;
using System;

namespace OpenAstroAra.Test {

    /// <summary>
    /// §45 — the ARA-owned polar-alignment geometry, proven against synthetic skies: pointings
    /// generated by Rodrigues rotation about a KNOWN axis must recover that axis exactly, the
    /// Bennett refraction term must match the almanac anchors, and the alt/az decomposition must
    /// reproduce closed-form meridian cases (independent of the implementation's own formulas).
    /// </summary>
    [TestFixture]
    public class PolarAlignGeometryTest {

        // ── synthetic-sky helpers ────────────────────────────────────────────────────────────

        private static (double X, double Y, double Z) Unit(double raDeg, double decDeg) {
            var ra = raDeg * Math.PI / 180.0;
            var dec = decDeg * Math.PI / 180.0;
            return (Math.Cos(dec) * Math.Cos(ra), Math.Cos(dec) * Math.Sin(ra), Math.Sin(dec));
        }

        private static (double RaDeg, double DecDeg) RaDec((double X, double Y, double Z) v) {
            var ra = Math.Atan2(v.Y, v.X) * 180.0 / Math.PI;
            if (ra < 0) ra += 360.0;
            return (ra, Math.Asin(Math.Clamp(v.Z, -1, 1)) * 180.0 / Math.PI);
        }

        // Rodrigues rotation of v about the unit axis k by angleDeg — the independent generator
        // the fit must invert.
        private static (double X, double Y, double Z) Rotate(
                (double X, double Y, double Z) v, (double X, double Y, double Z) k, double angleDeg) {
            var a = angleDeg * Math.PI / 180.0;
            var cos = Math.Cos(a);
            var sin = Math.Sin(a);
            var cross = (X: k.Y * v.Z - k.Z * v.Y, Y: k.Z * v.X - k.X * v.Z, Z: k.X * v.Y - k.Y * v.X);
            var dot = k.X * v.X + k.Y * v.Y + k.Z * v.Z;
            return (
                v.X * cos + cross.X * sin + k.X * dot * (1 - cos),
                v.Y * cos + cross.Y * sin + k.Y * dot * (1 - cos),
                v.Z * cos + cross.Z * sin + k.Z * dot * (1 - cos));
        }

        private static void AssertFitRecovers(double axisRa, double axisDec, double pointRa,
                double pointDec, double rotationDeg, bool north) {
            var axis = Unit(axisRa, axisDec);
            var p1 = Unit(pointRa, pointDec);
            var p2 = Rotate(p1, axis, rotationDeg);
            var (ra1, dec1) = RaDec(p1);
            var (ra2, dec2) = RaDec(p2);

            var fitted = PolarAlignGeometry.FitAxisTwoPoint(ra1, dec1, ra2, dec2, rotationDeg, north);

            // Compare as an angular separation, not per-component (RA degenerates near the pole).
            var sep = Math.Acos(Math.Clamp(
                Unit(fitted.RaDeg, fitted.DecDeg).X * axis.X
                + Unit(fitted.RaDeg, fitted.DecDeg).Y * axis.Y
                + Unit(fitted.RaDeg, fitted.DecDeg).Z * axis.Z, -1, 1)) * 180.0 / Math.PI;
            Assert.That(sep, Is.LessThan(1e-6),
                $"axis ({axisRa},{axisDec}) Δ={rotationDeg}° must be recovered exactly from noise-free pointings");
        }

        [Test]
        public void Two_point_fit_recovers_a_known_axis_across_geometries() {
            // A slightly-misaligned northern mount (the real use case): axis ~0.5° off the NCP.
            AssertFitRecovers(axisRa: 30, axisDec: 89.5, pointRa: 100, pointDec: 50, rotationDeg: 60, north: true);
            // Smaller + larger commanded rotations.
            AssertFitRecovers(30, 89.5, 100, 50, 30, true);
            AssertFitRecovers(30, 89.5, 100, 50, 90, true);
            // A worse initial alignment (2° off) and a pointing near the equator.
            AssertFitRecovers(210, 88.0, 350, 5, 60, true);
            // Southern hemisphere: axis near the SCP, disambiguated south.
            AssertFitRecovers(120, -89.3, 40, -40, 60, north: false);
        }

        [Test]
        public void Two_point_fit_handles_pointings_more_than_ninety_degrees_from_the_axis() {
            // The review's counterexample: axis at the true NCP, seed star at Dec −30° (θ = 120°
            // — a routine southern-declination choice while aligning north). The cosθ sign is
            // not recoverable from the chord, and the ghost axis line even reproduces the
            // rotation — the nearest-pole disambiguation must still return the NCP, not the
            // ~67°-away ghost the original single-sign construction picked.
            AssertFitRecovers(axisRa: 0, axisDec: 90, pointRa: 0, pointDec: -30, rotationDeg: 60, north: true);
            // The same regime on a realistically misaligned axis, both hemispheres.
            AssertFitRecovers(30, 89.5, 100, -30, 60, true);
            AssertFitRecovers(120, -89.3, 40, 25, 60, north: false);
        }

        [Test]
        public void Two_point_fit_refuses_an_axis_far_from_the_target_pole() {
            // An axis 60° from the pole violates the §45 rough-alignment precondition — the fit
            // must refuse rather than hand the bullseye a number it can't distinguish from the
            // ghost line.
            var axis = Unit(0, 30);
            var p1 = Unit(80, 60);
            var p2 = Rotate(p1, axis, 60);
            var (ra1, dec1) = RaDec(p1);
            var (ra2, dec2) = RaDec(p2);
            Assert.Throws<ArgumentOutOfRangeException>(() =>
                PolarAlignGeometry.FitAxisTwoPoint(ra1, dec1, ra2, dec2, 60, true));
        }

        [Test]
        public void Two_point_fit_rejects_degenerate_inputs() {
            Assert.Throws<ArgumentOutOfRangeException>(() =>
                PolarAlignGeometry.FitAxisTwoPoint(100, 50, 100, 50, 60, true),
                "coincident pointings carry no axis information");
            Assert.Throws<ArgumentOutOfRangeException>(() =>
                PolarAlignGeometry.FitAxisTwoPoint(100, 50, 120, 50, 0, true),
                "a zero rotation is meaningless");
            Assert.Throws<ArgumentOutOfRangeException>(() =>
                PolarAlignGeometry.FitAxisTwoPoint(100, 50, 120, 50, 180, true),
                "at 180° the short-way chord is ambiguous");
            // Pointings 90° apart cannot come from a 10° rotation — a bad solve must throw, not
            // silently produce a garbage axis the bullseye would chase.
            Assert.Throws<ArgumentOutOfRangeException>(() =>
                PolarAlignGeometry.FitAxisTwoPoint(0, 0, 90, 0, 10, true));
        }

        [Test]
        public void Bennett_matches_the_almanac_anchors() {
            // Horizon ≈ 34′ (the classic sunrise figure), 45° ≈ 1′, zenith ≈ 0.
            Assert.That(PolarAlignGeometry.BennettRefractionArcmin(0), Is.EqualTo(34.5).Within(0.5));
            Assert.That(PolarAlignGeometry.BennettRefractionArcmin(45), Is.EqualTo(0.96).Within(0.05));
            Assert.That(PolarAlignGeometry.BennettRefractionArcmin(90), Is.EqualTo(0).Within(0.06));
            Assert.Throws<ArgumentOutOfRangeException>(() => PolarAlignGeometry.BennettRefractionArcmin(-1));
        }

        // A fixed instant + site for the alt/az cases; LST enters only through "axis RA = LST"
        // constructions, so the exact value never appears in an expectation.
        private static readonly DateTimeOffset T = new(2026, 12, 21, 22, 0, 0, TimeSpan.Zero);
        private const double Lat = 45.0;
        private const double Lon = 0.0;

        [Test]
        public void An_axis_at_the_true_pole_reads_minus_refraction_in_altitude() {
            // The TRUE pole (dec +90) appears BELOW the refracted target by exactly Bennett(lat):
            // a mount aimed at the true pole still shows a small negative altitude error because
            // the solved sky it was measured against is refraction-lifted.
            var (altErr, azErr) = PolarAlignGeometry.AxisError(0, 90, Lat, Lon, T);
            Assert.That(altErr, Is.EqualTo(-PolarAlignGeometry.BennettRefractionArcmin(Lat)).Within(0.01));
            Assert.That(azErr, Is.EqualTo(0).Within(0.01));
        }

        [Test]
        public void A_meridian_offset_axis_reads_the_closed_form_altitude_error() {
            // Axis on the local meridian (RA = LST → hour angle 0), 10′ below the pole in dec:
            // at upper culmination above the pole, alt = lat + (90 − dec), so the altitude error
            // is +10′ − Bennett(lat). Closed form independent of the implementation's alt/az path.
            var lst = TonightSkyService.LocalSiderealTimeDeg(T, Lon);
            var (altErr, azErr) = PolarAlignGeometry.AxisError(lst, 90 - 10.0 / 60.0, Lat, Lon, T);
            Assert.That(altErr, Is.EqualTo(10.0 - PolarAlignGeometry.BennettRefractionArcmin(Lat)).Within(0.02));
            Assert.That(azErr, Is.EqualTo(0).Within(0.02));
        }

        [Test]
        public void Azimuth_error_mirrors_across_the_meridian() {
            // An off-meridian axis and its mirror (RA reflected about the LST) must read equal and
            // opposite azimuth errors and identical altitude errors — the knob-direction signs
            // cannot depend on which side of the meridian the measurement happened.
            var lst = TonightSkyService.LocalSiderealTimeDeg(T, Lon);
            var (altE, azE) = PolarAlignGeometry.AxisError(lst + 40, 89.7, Lat, Lon, T);
            var (altW, azW) = PolarAlignGeometry.AxisError(lst - 40, 89.7, Lat, Lon, T);
            Assert.That(azE, Is.EqualTo(-azW).Within(1e-6));
            Assert.That(altE, Is.EqualTo(altW).Within(1e-6));
            Assert.That(Math.Abs(azE), Is.GreaterThan(1.0), "a 0.3° off-pole axis at ±40° HA has a real az component");
        }

        [Test]
        public void End_to_end_a_synthetic_misalignment_round_trips_through_fit_and_error() {
            // Generate pointings from a KNOWN slightly-misaligned axis, fit it, decompose the
            // error — the whole §45 measurement pipeline on a synthetic sky. The recovered total
            // error must equal the constructed axis-to-apparent-pole separation.
            var lst = TonightSkyService.LocalSiderealTimeDeg(T, Lon);
            const double offArcmin = 25.0;
            var axisDec = 90 - offArcmin / 60.0;         // 25′ from the true pole, on the meridian
            var axis = Unit(lst, axisDec);
            var p1 = Unit(lst + 80, 40);
            var p2 = Rotate(p1, axis, 60);
            var (ra1, dec1) = RaDec(p1);
            var (ra2, dec2) = RaDec(p2);

            var fitted = PolarAlignGeometry.FitAxisTwoPoint(ra1, dec1, ra2, dec2, 60, true);
            var (altErr, azErr) = PolarAlignGeometry.AxisError(fitted.RaDeg, fitted.DecDeg, Lat, Lon, T);

            Assert.That(altErr, Is.EqualTo(offArcmin - PolarAlignGeometry.BennettRefractionArcmin(Lat)).Within(0.05));
            Assert.That(azErr, Is.EqualTo(0).Within(0.05));
        }

        [Test]
        public void AxisError_rejects_an_equatorial_site() {
            Assert.Throws<ArgumentOutOfRangeException>(() =>
                PolarAlignGeometry.AxisError(0, 90, 0, 0, T),
                "the celestial pole sits on the horizon at the equator — no alt/az decomposition");
        }
    }
}
