/// §61 settings registry. Single source of truth for every settable field
/// across all panels. Used for:
/// 1. Search index (Command Palette)
/// 2. Inline edit rendering
/// 3. Cross-linking hints
/// 4. Mechanical enforcement gate (COMMIT-PR-RULES.md)
library;

enum SettingTypeKind {
  bool,
  intRange,
  doubleRange,
  enumValue,
  string,
  duration,
  color,
  keyboardShortcut,
  path,
  complex,
}

class SettingType {
  final SettingTypeKind kind;
  final num? min;
  final num? max;
  final num? step;
  final List<String>? enumValues;

  const SettingType.bool() : kind = SettingTypeKind.bool, min = null, max = null, step = null, enumValues = null;
  // ignore: prefer_initializing_formals
  const SettingType.intRange({required int min, required int max}) : kind = SettingTypeKind.intRange, min = min, max = max, step = 1, enumValues = null;
  // ignore: prefer_initializing_formals
  const SettingType.doubleRange({required double min, required double max, double step = 0.1}) : kind = SettingTypeKind.doubleRange, min = min, max = max, step = step, enumValues = null;
  const SettingType.enumValue(List<String> values) : kind = SettingTypeKind.enumValue, min = null, max = null, step = null, enumValues = values;
  const SettingType.string() : kind = SettingTypeKind.string, min = null, max = null, step = null, enumValues = null;
  const SettingType.duration() : kind = SettingTypeKind.duration, min = null, max = null, step = null, enumValues = null;
  const SettingType.path() : kind = SettingTypeKind.path, min = null, max = null, step = null, enumValues = null;
  const SettingType.complex() : kind = SettingTypeKind.complex, min = null, max = null, step = null, enumValues = null;
}

class Setting {
  final String id;
  final String label;
  final String description;
  final List<String> keywords;
  final List<String> path;
  final SettingType type;
  final dynamic defaultValue;
  final String? profilePath;
  final List<String> relatedSettings;

  const Setting({
    required this.id,
    required this.label,
    required this.description,
    required this.keywords,
    required this.path,
    required this.type,
    required this.defaultValue,
    this.profilePath,
    this.relatedSettings = const <String>[],
  });
}

/// The canonical settings registry.
const List<Setting> settingsRegistry = [
  // §35 Safety Policies — 12 fields covering unsafe weather + meridian flip
  // + altitude limit + guider loss. State lives in `safetyPoliciesProvider`.
  Setting(
    id: 'safety.policies.on_unsafe',
    label: 'On unsafe weather',
    description: 'What action to take when the §35 safety monitor reports unsafe conditions (rain, wind, clouds, humidity past dew point).',
    keywords: ['unsafe', 'weather', 'pause', 'park', 'abort', 'dome', 'rain', 'wind', 'safety'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.enumValue(['Pause + park', 'Park only', 'Abort + park', 'Ignore']),
    defaultValue: 'Pause + park',
    profilePath: 'safety.on_unsafe',
  ),
  Setting(
    id: 'safety.policies.auto_resume',
    label: 'Auto-resume when safe',
    description: 'Automatically resume the paused sequence when the safety monitor reports safe again. Off = manual unpause required.',
    keywords: ['resume', 'safe', 'automatic', 'weather', 'restart'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'safety.auto_resume',
  ),
  Setting(
    id: 'safety.policies.resume_delay',
    label: 'Resume delay (min)',
    description: 'Minutes to wait after the "safe" signal before actually resuming. Lets a passing cloud bank fully clear.',
    keywords: ['delay', 'wait', 'resume', 'safe', 'minutes'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.intRange(min: 0, max: 60),
    defaultValue: 10,
    profilePath: 'safety.resume_delay_min',
  ),
  Setting(
    id: 'safety.policies.meridian_flip_auto',
    label: 'Auto meridian flip',
    description: 'Automatically execute the meridian flip when the target crosses the meridian. Off = sequence pauses and waits for manual flip.',
    keywords: ['meridian', 'flip', 'auto', 'pier', 'side', 'german equatorial', 'gem'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'safety.meridian_flip_auto',
  ),
  Setting(
    id: 'safety.policies.meridian_pause_min',
    label: 'Pause after meridian flip (min)',
    description: 'Minutes to wait after a meridian flip before resuming exposures, so the mount can settle + the guider can re-lock.',
    keywords: ['meridian', 'flip', 'pause', 'wait', 'settle', 'minutes'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.intRange(min: 0, max: 30),
    defaultValue: 5,
    profilePath: 'safety.meridian_pause_min',
  ),
  Setting(
    id: 'safety.policies.meridian_recenter',
    label: 'Re-center after meridian flip',
    description: 'Plate-solve and re-center the target after a meridian flip. Compensates for pointing shifts caused by the mount\'s pier-side swap.',
    keywords: ['meridian', 'flip', 'recenter', 'plate solve', 'pointing', 'pier'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'safety.meridian_recenter',
  ),
  Setting(
    id: 'safety.policies.meridian_recal_guider',
    label: 'Re-calibrate guider after flip',
    description: 'Re-run PHD2 calibration after a meridian flip. Necessary because guide directions reverse on the new pier side.',
    keywords: ['meridian', 'flip', 'guider', 'calibration', 'phd2', 'recalibrate'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'safety.meridian_recal_guider',
  ),
  Setting(
    id: 'safety.policies.flip_safety_enabled',
    label: 'Unattended flip safety (§58.9)',
    description: 'Protects a sleeping user: a pre-flip flight check (target altitude, mount health, required equipment), an in-slew watchdog (stall + timeout abort) and a hard pier-side verification. Turn off only if this mount misreports pier side.',
    keywords: ['meridian', 'flip', 'safety', 'unattended', 'watchdog', 'flight check', 'pier side', 'overnight'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'safety.flip_safety_enabled',
    relatedSettings: ['safety.policies.meridian_flip_auto', 'safety.policies.expected_flip_slew_seconds'],
  ),
  Setting(
    id: 'safety.policies.expected_flip_slew_seconds',
    label: 'Expected flip-slew duration (s)',
    description: 'How long this mount typically takes to complete the meridian-flip slew. The flip watchdog aborts a slew that exceeds 3× this value (capped at 5 minutes) — Alpaca mounts do not report their own estimate.',
    keywords: ['meridian', 'flip', 'slew', 'duration', 'timeout', 'watchdog', 'safety'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.intRange(min: 1, max: 300),
    defaultValue: 90,
    profilePath: 'safety.expected_flip_slew_seconds',
    relatedSettings: ['safety.policies.flip_safety_enabled'],
  ),
  Setting(
    id: 'safety.policies.unattended_escalation',
    label: 'Louder alerts during dark hours (§58.10)',
    description: 'While the site sits in astronomical darkness (sun below −18°), equipment-impacting warnings are raised one severity level (warning→error, error→critical) so the bedside alarm behaviour engages earlier for a sleeping user. Escalated messages say why; daytime severities are untouched.',
    keywords: ['unattended', 'night', 'severity', 'escalation', 'alarm', 'overnight', 'dark', 'notification', 'sleeping'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'safety.unattended_escalation',
    relatedSettings: ['safety.policies.flip_safety_enabled'],
  ),
  Setting(
    id: 'safety.policies.first_flip_confirmed',
    label: 'First-flip announce (§58.8)',
    description: 'The very first meridian flip on a profile posts a critical alert and waits 60 seconds before proceeding — cheap insurance against a wrong pause value flipping the OTA into the tripod. Runs once; changing the optics train (or the Re-arm button here) arms it again.',
    keywords: ['meridian', 'flip', 'first', 'confirm', 'announce', 'safety', 'new profile', 're-arm', 'tripod'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.bool(),
    defaultValue: false,
    profilePath: 'safety.first_flip_confirmed',
    relatedSettings: ['safety.policies.flip_safety_enabled', 'safety.policies.meridian_flip_auto'],
  ),
  Setting(
    id: 'safety.policies.on_altitude_limit',
    label: 'On altitude limit',
    description: 'Action when a target drops below the §37.12 minimum-altitude floor.',
    keywords: ['altitude', 'limit', 'horizon', 'skip', 'pause', 'abort', 'low'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.enumValue(['Skip target', 'Pause sequence', 'Abort sequence']),
    defaultValue: 'Skip target',
    profilePath: 'safety.on_altitude_limit',
  ),
  Setting(
    id: 'safety.policies.park_if_no_more_targets',
    label: 'Park when no more targets',
    description: 'Park the mount when the sequence runs out of remaining targets (e.g. all targets dropped below altitude floor). Otherwise the mount stays tracking until session end.',
    keywords: ['park', 'no targets', 'sequence end', 'idle'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'safety.park_if_no_more_targets',
  ),
  Setting(
    id: 'safety.policies.on_guider_lost',
    label: 'On guider lost',
    description: 'Action when the guider loses lock (clouds, star drift, calibration glitch).',
    keywords: ['guider', 'lost', 'phd2', 'pause', 'retry', 'skip', 'abort'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.enumValue(['Pause + retry', 'Skip target', 'Abort sequence']),
    defaultValue: 'Pause + retry',
    profilePath: 'safety.on_guider_lost',
  ),
  Setting(
    id: 'safety.policies.on_disk_space_critical',
    label: 'On critically-low disk',
    description: 'Action when free space on the save volume hits the §29 critical threshold: warn only, or also abort the running sequence.',
    keywords: ['disk', 'space', 'storage', 'full', 'critical', 'abort', 'halt', 'stop', 'sequence'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.enumValue(['Warn only', 'Abort the running sequence']),
    defaultValue: 'Warn only',
    profilePath: 'safety.on_disk_space_critical',
  ),
  Setting(
    id: 'safety.policies.guider_retry_timeout',
    label: 'Guider retry timeout (s)',
    description: 'How long to keep retrying guider re-acquisition before giving up. Tied to the §54 plate-solve-failed notification trigger.',
    keywords: ['guider', 'retry', 'timeout', 'phd2', 'seconds'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.intRange(min: 0, max: 600),
    defaultValue: 60,
    profilePath: 'safety.guider_retry_timeout_sec',
  ),
  Setting(
    id: 'safety.policies.skip_target_if_recovery_fails',
    label: 'Skip target if recovery fails',
    description: 'When guider retry timeout expires, skip the target and try the next instead of aborting the whole sequence.',
    keywords: ['skip', 'target', 'recovery', 'guider', 'fail', 'continue'],
    path: ['Settings', 'Safety', 'Policies'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'safety.skip_target_if_recovery_fails',
  ),

  // §51 Diagnostics — single-enum picker; actual state lives in
  // `diagnosticsModeProvider`.
  Setting(
    id: 'diagnostics.mode',
    label: 'Diagnostics mode',
    description: 'How Ara responds to §51 critical-severity diagnostic events (sensor temp out of range, mount drift, etc).',
    keywords: ['diagnostics', 'mode', 'severity', 'notify', 'pause', 'abort', 'critical', 'recovery'],
    path: ['Settings', 'Safety', 'Diagnostics'],
    type: SettingType.enumValue(['Notify only', 'Pause on critical', 'Abort on critical']),
    defaultValue: 'Notify only',
    profilePath: 'diagnostics.mode',
  ),

  // §37.9 Imaging Defaults — 8 fields. State lives in `imagingDefaultsProvider`.
  Setting(
    id: 'imaging.defaults.exposure',
    label: 'Default exposure (s)',
    description: 'Seed exposure time for the Imaging tab when no target-specific override exists. New sequences inherit this.',
    keywords: ['exposure', 'time', 'seconds', 'default', 'shutter'],
    path: ['Settings', 'Imaging', 'Defaults'],
    type: SettingType.intRange(min: 1, max: 3600),
    defaultValue: 5,
    profilePath: 'imaging.default_exposure_s',
  ),
  Setting(
    id: 'imaging.defaults.gain',
    label: 'Default gain',
    description: 'CMOS sensor gain in camera units. Higher = more sensitivity but more read noise. Range depends on the camera.',
    keywords: ['gain', 'sensitivity', 'iso', 'amplification', 'cmos'],
    path: ['Settings', 'Imaging', 'Defaults'],
    type: SettingType.intRange(min: 0, max: 1000),
    defaultValue: 100,
    profilePath: 'imaging.default_gain',
  ),
  Setting(
    id: 'imaging.defaults.offset',
    label: 'Default offset',
    description: 'Sensor offset (pedestal) — keeps the black level off zero so subtraction operations don\'t clip. Camera-specific.',
    keywords: ['offset', 'pedestal', 'bias', 'black level', 'cmos'],
    path: ['Settings', 'Imaging', 'Defaults'],
    type: SettingType.intRange(min: 0, max: 500),
    defaultValue: 50,
    profilePath: 'imaging.default_offset',
  ),
  Setting(
    id: 'imaging.defaults.bin',
    label: 'Default binning',
    description: 'Pixel binning factor. 1 = native (full resolution); 2 = 2x2 grouped pixels, more sensitivity, less resolution.',
    keywords: ['bin', 'binning', 'resolution', 'pixel', 'downsample'],
    path: ['Settings', 'Imaging', 'Defaults'],
    type: SettingType.intRange(min: 1, max: 4),
    defaultValue: 1,
    profilePath: 'imaging.default_bin',
  ),
  Setting(
    id: 'imaging.defaults.frame_kind',
    label: 'Default frame type',
    description: 'Frame type for the next exposure: light (target), dark (calibration with shutter closed), bias (zero-second), flat (uniform field).',
    keywords: ['frame', 'type', 'light', 'dark', 'bias', 'flat', 'calibration'],
    path: ['Settings', 'Imaging', 'Defaults'],
    type: SettingType.enumValue(['Light', 'Dark', 'Bias', 'Flat']),
    defaultValue: 'Light',
    profilePath: 'imaging.default_frame_kind',
  ),
  Setting(
    id: 'imaging.defaults.cooler_target_c',
    label: 'Cooling target (°C)',
    description: 'Sensor target temperature when the cooler is active. Typical: -10°C to -20°C depending on the sensor and ambient.',
    keywords: ['cooler', 'temperature', 'target', 'celsius', 'cooling', 'tec'],
    path: ['Settings', 'Imaging', 'Defaults'],
    type: SettingType.doubleRange(min: -60, max: 30, step: 1),
    defaultValue: -10.0,
    profilePath: 'imaging.cooler_target_c',
  ),
  Setting(
    id: 'imaging.defaults.cooler_ramp_c_per_min',
    label: 'Cooler ramp rate (°C/min)',
    description: 'How fast to step the cooler toward the target. Slow ramps avoid thermal shock + condensation on the sensor cover.',
    keywords: ['ramp', 'cooler', 'thermal shock', 'condensation', 'cooldown'],
    path: ['Settings', 'Imaging', 'Defaults'],
    type: SettingType.doubleRange(min: 0, max: 10, step: 0.5),
    defaultValue: 1.0,
    profilePath: 'imaging.cooler_ramp_c_per_min',
  ),
  Setting(
    id: 'imaging.defaults.warmup_at_session_end',
    label: 'Warm-up cooler at session end',
    description: 'Ramp the sensor back to ambient at the end of a session instead of disconnecting cold. CCDs need this; CMOS usually don\'t.',
    keywords: ['warmup', 'cooler', 'shutdown', 'thermal shock', 'session end', 'ccd', 'cmos'],
    path: ['Settings', 'Imaging', 'Defaults'],
    type: SettingType.bool(),
    defaultValue: false,
    profilePath: 'imaging.warmup_at_session_end',
  ),

  // §36/§25.5 Optics — 5 fields driving the Planning Frame-mode FOV box.
  // State lives in `opticsSettingsProvider`; profile section is `optics` (#467).
  Setting(
    id: 'img.optics.focal_length_mm',
    label: 'Focal length (mm)',
    description: 'Telescope focal length before any reducer or barlow. Sets the image scale and field of view shown in the Planning Frame overlay.',
    keywords: ['optics', 'focal length', 'telescope', 'fov', 'field of view', 'framing', 'scale'],
    path: ['Settings', 'Imaging', 'Optics'],
    type: SettingType.doubleRange(min: 0, max: 10000, step: 1),
    defaultValue: 0.0,
    profilePath: 'optics.focal_length_mm',
  ),
  Setting(
    id: 'img.optics.reducer_factor',
    label: 'Reducer / barlow factor (×)',
    description: 'Multiplier on the focal length: 1.0 for none, 0.8 for a 0.8× reducer, 2.0 for a 2× barlow. Must be greater than 0.',
    keywords: ['optics', 'reducer', 'barlow', 'focal reducer', 'fov', 'framing'],
    path: ['Settings', 'Imaging', 'Optics'],
    type: SettingType.doubleRange(min: 0.1, max: 5, step: 0.1),
    defaultValue: 1.0,
    profilePath: 'optics.reducer_factor',
  ),
  Setting(
    id: 'img.optics.sensor_width_px',
    label: 'Sensor width (px)',
    description: 'Camera sensor width in pixels. Combined with the pixel size and focal length to draw the field-of-view rectangle on the atlas.',
    keywords: ['optics', 'sensor', 'width', 'pixels', 'camera', 'fov', 'framing'],
    path: ['Settings', 'Imaging', 'Optics'],
    type: SettingType.intRange(min: 0, max: 100000),
    defaultValue: 0,
    profilePath: 'optics.sensor_width_px',
  ),
  Setting(
    id: 'img.optics.sensor_height_px',
    label: 'Sensor height (px)',
    description: 'Camera sensor height in pixels. Combined with the pixel size and focal length to draw the field-of-view rectangle on the atlas.',
    keywords: ['optics', 'sensor', 'height', 'pixels', 'camera', 'fov', 'framing'],
    path: ['Settings', 'Imaging', 'Optics'],
    type: SettingType.intRange(min: 0, max: 100000),
    defaultValue: 0,
    profilePath: 'optics.sensor_height_px',
  ),
  Setting(
    id: 'img.optics.pixel_size_um',
    label: 'Pixel size (µm)',
    description: 'Sensor pixel pitch in microns. Sets the per-pixel image scale (206.265 × pixel size ÷ focal length) used by the Planning Frame overlay.',
    keywords: ['optics', 'pixel size', 'pitch', 'microns', 'camera', 'scale', 'fov'],
    path: ['Settings', 'Imaging', 'Optics'],
    type: SettingType.doubleRange(min: 0, max: 50, step: 0.1),
    defaultValue: 0.0,
    profilePath: 'optics.pixel_size_um',
  ),
  Setting(
    id: 'img.optics.aperture_mm',
    label: 'Aperture (mm)',
    description: 'Telescope objective diameter. Feeds the sky-flux term of the Optimal Sub exposure calculator (Glover read-noise criterion) — framing works without it, exposure advice does not.',
    keywords: ['optics', 'aperture', 'objective', 'diameter', 'f-ratio', 'optimal sub', 'exposure', 'glover'],
    path: ['Settings', 'Imaging', 'Optics'],
    type: SettingType.doubleRange(min: 0, max: 2000, step: 1),
    defaultValue: 0.0,
    profilePath: 'optics.aperture_mm',
    relatedSettings: ['img.optics.focal_length_mm', 'img.electronics.read_noise_e'],
  ),

  // NEXTGEN §3/§4 Camera electronics — exposure-planning inputs behind the
  // Optimal Sub calculator. State lives in `cameraElectronicsProvider`.
  Setting(
    id: 'img.electronics.sensor_name',
    label: 'Sensor name',
    description: 'Sensor model reported by the camera driver (e.g. IMX571). Auto-filled when a camera connects; identifies which sensor the electronics values describe.',
    keywords: ['camera', 'sensor', 'name', 'model', 'electronics', 'imx'],
    path: ['Settings', 'Imaging', 'Camera electronics'],
    type: SettingType.string(),
    defaultValue: '',
    profilePath: 'camera_electronics.sensor_name',
  ),
  Setting(
    id: 'img.electronics.read_noise_e',
    label: 'Read noise (e⁻ RMS)',
    description: 'Camera read noise in electrons at the stated gain, from the manufacturer\'s gain chart or a SharpCap sensor analysis. Sets the Optimal Sub read-noise floor (t = 10·R²/P, criterion popularised by Dr. Robin Glover).',
    keywords: ['read noise', 'camera', 'electronics', 'noise', 'optimal sub', 'exposure', 'glover', 'sharpcap'],
    path: ['Settings', 'Imaging', 'Camera electronics'],
    type: SettingType.doubleRange(min: 0, max: 100, step: 0.1),
    defaultValue: 0.0,
    profilePath: 'camera_electronics.read_noise_e',
    relatedSettings: ['img.electronics.full_well_e', 'img.optics.aperture_mm'],
  ),
  Setting(
    id: 'img.electronics.full_well_e',
    label: 'Full-well capacity (e⁻)',
    description: 'Sensor full-well depth in electrons for the current readout mode — auto-filled from the connected camera (High Full Well modes re-capture on reconnect). Sets the Optimal Sub saturation ceiling.',
    keywords: ['full well', 'capacity', 'saturation', 'camera', 'electronics', 'optimal sub', 'exposure', 'hfw'],
    path: ['Settings', 'Imaging', 'Camera electronics'],
    type: SettingType.doubleRange(min: 0, max: 1000000, step: 100),
    defaultValue: 0.0,
    profilePath: 'camera_electronics.full_well_e',
  ),
  Setting(
    id: 'img.electronics.electrons_per_adu',
    label: 'Conversion gain (e⁻/ADU)',
    description: 'Electrons per ADU at the stated gain — auto-filled from the connected camera. Clips the effective well to what the 16-bit ADC can actually record.',
    keywords: ['gain', 'e/adu', 'adu', 'conversion', 'camera', 'electronics', 'adc'],
    path: ['Settings', 'Imaging', 'Camera electronics'],
    type: SettingType.doubleRange(min: 0, max: 100, step: 0.01),
    defaultValue: 0.0,
    profilePath: 'camera_electronics.electrons_per_adu',
  ),
  Setting(
    id: 'img.electronics.gain',
    label: 'Gain these values apply at',
    description: 'The camera gain setting the read noise / full well / e⁻/ADU describe — they change with gain, so exposure advice notes when your sequence uses a different one. −1 means unset.',
    keywords: ['gain', 'camera', 'electronics', 'iso', 'readout'],
    path: ['Settings', 'Imaging', 'Camera electronics'],
    type: SettingType.intRange(min: -1, max: 10000),
    defaultValue: -1,
    profilePath: 'camera_electronics.gain',
  ),
  Setting(
    id: 'img.electronics.qe_peak',
    label: 'Peak quantum efficiency (0–1)',
    description: 'Sensor peak QE as a fraction, from the manufacturer\'s spec sheet (0.8 is a typical modern CMOS). Scales the sky-flux estimate in the Optimal Sub calculator.',
    keywords: ['quantum efficiency', 'qe', 'sensor', 'camera', 'electronics', 'optimal sub'],
    path: ['Settings', 'Imaging', 'Camera electronics'],
    type: SettingType.doubleRange(min: 0, max: 1, step: 0.01),
    defaultValue: 0.0,
    profilePath: 'camera_electronics.quantum_efficiency_peak',
  ),

  // NEXTGEN §1/§4 Planning filter set — one composite list setting (the panel
  // is a list editor, not per-field rows). State lives in `filterSetProvider`.
  Setting(
    id: 'img.filterset.filters',
    label: 'Planning filter set',
    description: 'The filters you image with (name, kind, effective bandwidth). Drives narrowband-vs-broadband planning advice in Tonight\'s Sky and the per-filter Optimal Sub; names match sequences case-insensitively, so mirror your wheel labels.',
    keywords: ['filters', 'filter set', 'narrowband', 'broadband', 'dual band', 'ha', 'oiii', 'sii', 'l-extreme', 'l-enhance', 'planning', 'optimal sub'],
    path: ['Settings', 'Imaging', 'Filter set'],
    type: SettingType.complex(),
    defaultValue: null,
    profilePath: 'filter_set.filters',
    relatedSettings: ['img.electronics.read_noise_e', 'img.optics.aperture_mm'],
  ),

  // §29 Storage — 4 fields. State lives in `storageSettingsProvider`.
  Setting(
    id: 'session.storage.save_directory',
    label: 'Save directory',
    description: 'Base directory where captured frames are written. The §29.1.3 ext4 wizard helps migrate from the SD card to a USB drive.',
    keywords: ['save', 'directory', 'folder', 'path', 'storage', 'disk', 'usb', 'sd card'],
    path: ['Settings', 'Session', 'Storage'],
    type: SettingType.path(),
    defaultValue: '/media/openastroara',
    profilePath: 'storage.save_directory',
  ),
  Setting(
    id: 'session.storage.file_format',
    label: 'File format',
    description: 'On-disk frame format. FITS is the de-facto astronomy standard; XISF is PixInsight\'s native format with richer metadata.',
    keywords: ['format', 'fits', 'xisf', 'rice', 'gzip', 'file type', 'extension'],
    path: ['Settings', 'Session', 'Storage'],
    type: SettingType.enumValue(['FITS', 'XISF', 'FITS + RICE compression', 'FITS + gzip']),
    defaultValue: 'FITS',
    profilePath: 'storage.file_format',
  ),
  Setting(
    id: 'session.storage.compression',
    label: 'Compression',
    description: 'Optional lossless compression of frame files at write time. RICE is fast + astronomy-tuned; gzip is universal but slower.',
    keywords: ['compression', 'rice', 'gzip', 'lossless', 'disk space', 'size'],
    path: ['Settings', 'Session', 'Storage'],
    type: SettingType.enumValue(['Off', 'RICE', 'gzip']),
    defaultValue: 'RICE',
    profilePath: 'storage.compression',
  ),
  Setting(
    id: 'session.storage.filename_template',
    label: 'Filename template',
    description: 'Pattern for output filenames using \$\$TOKEN\$\$ placeholders. Tokens: DATEMINUS12, DATETIME, IMAGETYPE, FILTER, EXPOSURETIME, TARGETNAME, etc.',
    keywords: ['filename', 'template', 'naming', 'tokens', 'pattern', 'date', 'filter'],
    path: ['Settings', 'Session', 'Storage'],
    type: SettingType.string(),
    // Raw string matches `StorageSettings.filenameTemplate` default verbatim.
    // The doubled-backslash + doubled-dollar syntax is the template engine's
    // own convention (`\\` as path separator, `$$TOKEN$$` for substitution);
    // the `r''` prefix means Dart doesn't process either as escapes.
    defaultValue: r'$$DATEMINUS12$$\\$$IMAGETYPE$$\\$$DATETIME$$_$$FILTER$$_$$EXPOSURETIME$$s',
    profilePath: 'storage.filename_template',
  ),
  Setting(
    id: 'session.storage.min_free_disk_warn_gb',
    label: 'Low-disk warning threshold (GB)',
    description: 'Free space on the save volume below which the daemon raises a low-disk warning. Must be above the critical threshold.',
    keywords: ['disk', 'space', 'storage', 'free', 'warn', 'low', 'threshold', 'gb'],
    path: ['Settings', 'Session', 'Storage'],
    type: SettingType.intRange(min: 1, max: 100000),
    defaultValue: 10,
    profilePath: 'storage.min_free_disk_warn_gb',
  ),
  Setting(
    id: 'session.storage.min_free_disk_critical_gb',
    label: 'Critical-disk threshold (GB)',
    description: 'Free space on the save volume below which the daemon raises a critical low-disk alert. Must be below the warning threshold.',
    keywords: ['disk', 'space', 'storage', 'free', 'critical', 'low', 'threshold', 'gb'],
    path: ['Settings', 'Session', 'Storage'],
    type: SettingType.intRange(min: 1, max: 100000),
    defaultValue: 2,
    profilePath: 'storage.min_free_disk_critical_gb',
  ),

  // §54 Notifications — 12 fields (5 channels + 7 triggers). State lives in
  // `notificationsSettingsProvider`.
  // Channels.
  Setting(
    id: 'session.notifications.in_app_banner',
    label: 'In-app banner',
    description: 'Show a transient banner inside Ara when an event fires.',
    keywords: ['banner', 'in-app', 'notification', 'toast', 'popup'],
    path: ['Settings', 'Session', 'Notifications'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'notifications.in_app_banner',
  ),
  Setting(
    id: 'session.notifications.os_desktop',
    label: 'OS desktop notification',
    description: 'Send a native OS notification (macOS Notification Center / Linux libnotify / Windows toast) when an event fires.',
    keywords: ['desktop', 'os', 'notification', 'native', 'system', 'tray', 'toast'],
    path: ['Settings', 'Session', 'Notifications'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'notifications.os_desktop',
  ),
  Setting(
    id: 'session.notifications.sound_alert',
    label: 'Sound alert',
    description: 'Play the §35 alarm sound on safety/critical events. Independent of OS notification sound.',
    keywords: ['sound', 'alarm', 'audio', 'alert', 'beep'],
    path: ['Settings', 'Session', 'Notifications'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'notifications.sound_alert',
  ),
  Setting(
    id: 'session.notifications.pushover_token',
    label: 'Pushover token',
    description: 'Pushover user key for push notifications to phone. Leave empty to disable.',
    keywords: ['pushover', 'token', 'phone', 'mobile', 'push', 'remote'],
    path: ['Settings', 'Session', 'Notifications'],
    type: SettingType.string(),
    defaultValue: '',
    profilePath: 'notifications.pushover_token',
  ),
  Setting(
    id: 'session.notifications.telegram_bot_token',
    label: 'Telegram bot token',
    description: 'Telegram bot token for sending messages to your chat. Leave empty to disable.',
    keywords: ['telegram', 'bot', 'token', 'chat', 'remote', 'mobile'],
    path: ['Settings', 'Session', 'Notifications'],
    type: SettingType.string(),
    defaultValue: '',
    profilePath: 'notifications.telegram_bot_token',
  ),
  // Triggers.
  Setting(
    id: 'session.notifications.on_sequence_complete',
    label: 'Trigger on sequence complete',
    description: 'Notify when a sequence finishes its last instruction.',
    keywords: ['sequence', 'complete', 'finish', 'done', 'trigger'],
    path: ['Settings', 'Session', 'Notifications'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'notifications.on_sequence_complete',
  ),
  Setting(
    id: 'session.notifications.on_sequence_paused',
    label: 'Trigger on sequence paused',
    description: 'Notify when a sequence pauses (user request, safety policy, or meridian flip wait).',
    keywords: ['sequence', 'paused', 'pause', 'wait', 'trigger'],
    path: ['Settings', 'Session', 'Notifications'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'notifications.on_sequence_paused',
  ),
  Setting(
    id: 'session.notifications.on_critical_diagnostic',
    label: 'Trigger on critical diagnostic',
    description: 'Notify on §51 critical-severity diagnostic events (sensor temp out of range, mount drift, etc).',
    keywords: ['diagnostic', 'critical', 'severity', 'fault', 'health', 'trigger'],
    path: ['Settings', 'Session', 'Notifications'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'notifications.on_critical_diagnostic',
  ),
  Setting(
    id: 'session.notifications.on_safety_event',
    label: 'Trigger on safety event',
    description: 'Notify when the §35 safety monitor reports unsafe weather, an altitude limit, or guider loss.',
    keywords: ['safety', 'weather', 'unsafe', 'park', 'alarm', 'trigger'],
    path: ['Settings', 'Session', 'Notifications'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'notifications.on_safety_event',
  ),
  Setting(
    id: 'session.notifications.on_autofocus_failed',
    label: 'Trigger on autofocus failed',
    description: 'Notify when an autofocus run gives up without converging.',
    keywords: ['autofocus', 'failed', 'focus', 'hfr', 'trigger'],
    path: ['Settings', 'Session', 'Notifications'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'notifications.on_autofocus_failed',
  ),
  Setting(
    id: 'session.notifications.on_plate_solve_failed',
    label: 'Trigger on plate solve failed',
    description: 'Notify when the plate solver fails N times in a row (per §35 guider-lost retry budget).',
    keywords: ['plate solve', 'failed', 'astrometry', 'astap', 'retry', 'trigger'],
    path: ['Settings', 'Session', 'Notifications'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'notifications.on_plate_solve_failed',
  ),
  Setting(
    id: 'session.notifications.on_disk_space_low',
    label: 'Trigger on disk space low',
    description: 'Notify when free space on the save directory drops below ~10 GB.',
    keywords: ['disk', 'space', 'low', 'storage', 'full', 'free', 'trigger'],
    path: ['Settings', 'Session', 'Notifications'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'notifications.on_disk_space_low',
  ),

  // §37.12 Site preferences — 10 fields. State lives in `siteSettingsProvider`.
  Setting(
    id: 'safety.site.site_name',
    label: 'Site name',
    description: 'Friendly label for the observing location. Used in session metadata + FITS header SITE keyword.',
    keywords: ['site', 'name', 'location', 'place', 'observatory'],
    path: ['Settings', 'Safety', 'Site'],
    type: SettingType.string(),
    defaultValue: 'Backyard',
    profilePath: 'site.name',
  ),
  Setting(
    id: 'safety.site.latitude_deg',
    label: 'Latitude (°)',
    description: 'Site latitude in decimal degrees. North positive (+), south negative (−). Used for hour-angle, twilight, and altitude calculations.',
    keywords: ['latitude', 'lat', 'location', 'gps', 'decimal degrees', 'coordinates'],
    path: ['Settings', 'Safety', 'Site'],
    type: SettingType.doubleRange(min: -90, max: 90, step: 0.000001),
    defaultValue: 0.0,
    profilePath: 'site.latitude_deg',
  ),
  Setting(
    id: 'safety.site.longitude_deg',
    label: 'Longitude (°)',
    description: 'Site longitude in decimal degrees. East positive (+), west negative (−). Used for sidereal time + meridian flip calculations.',
    keywords: ['longitude', 'lon', 'lng', 'location', 'gps', 'decimal degrees', 'coordinates'],
    path: ['Settings', 'Safety', 'Site'],
    type: SettingType.doubleRange(min: -180, max: 180, step: 0.000001),
    defaultValue: 0.0,
    profilePath: 'site.longitude_deg',
  ),
  Setting(
    id: 'safety.site.elevation_m',
    label: 'Elevation (m)',
    description: 'Height above sea level. Used for atmospheric refraction corrections in §38 framing + plate-solve fitting.',
    keywords: ['elevation', 'altitude', 'height', 'meters', 'sea level', 'asl'],
    path: ['Settings', 'Safety', 'Site'],
    type: SettingType.doubleRange(min: -500, max: 9000, step: 1),
    defaultValue: 0.0,
    profilePath: 'site.elevation_m',
  ),
  Setting(
    id: 'safety.site.time_zone',
    label: 'Time zone',
    description: 'IANA time zone identifier (e.g. America/Los_Angeles). Used for session-local timestamps + scheduling.',
    keywords: ['time zone', 'timezone', 'iana', 'tz', 'utc', 'dst'],
    path: ['Settings', 'Safety', 'Site'],
    type: SettingType.string(),
    defaultValue: 'UTC',
    profilePath: 'site.time_zone',
  ),
  Setting(
    id: 'safety.site.use_custom_horizon',
    label: 'Use custom horizon polygon',
    description: 'When on, target visibility uses the imported azimuth/altitude polygon (§36.8) instead of the flat default-altitude floor.',
    keywords: ['horizon', 'custom', 'polygon', 'mask', 'obstruction', 'trees', 'building'],
    path: ['Settings', 'Safety', 'Site'],
    type: SettingType.bool(),
    defaultValue: false,
    profilePath: 'site.use_custom_horizon',
  ),
  Setting(
    id: 'safety.site.default_horizon_altitude_deg',
    label: 'Default horizon altitude (°)',
    description: 'Flat horizon floor used when no custom polygon is loaded. Targets below this altitude are flagged as below-horizon.',
    keywords: ['horizon', 'altitude', 'floor', 'minimum', 'limit', 'degrees'],
    path: ['Settings', 'Safety', 'Site'],
    type: SettingType.doubleRange(min: 0, max: 90, step: 1),
    defaultValue: 20.0,
    profilePath: 'site.default_horizon_altitude_deg',
  ),
  Setting(
    id: 'safety.site.bortle_class',
    label: 'Bortle class',
    description: 'Bortle dark-sky classification, 1 (excellent dark site) through 9 (inner-city). Used for SNR estimation + suggested exposure ranges.',
    keywords: ['bortle', 'dark sky', 'light pollution', 'sqm', 'class', 'sky quality'],
    path: ['Settings', 'Safety', 'Site'],
    type: SettingType.intRange(min: 1, max: 9),
    defaultValue: 6,
    profilePath: 'site.bortle_class',
  ),
  Setting(
    id: 'safety.site.typical_seeing_arcsec',
    label: 'Typical seeing (″)',
    description: 'Median atmospheric seeing FWHM in arcseconds at this site. Used for §50 quality-score baselining + autofocus convergence.',
    keywords: ['seeing', 'fwhm', 'atmosphere', 'turbulence', 'arcsec', 'quality'],
    path: ['Settings', 'Safety', 'Site'],
    type: SettingType.doubleRange(min: 0, max: 20, step: 0.1),
    defaultValue: 2.5,
    profilePath: 'site.typical_seeing_arcsec',
  ),
  Setting(
    id: 'safety.site.twilight_definition',
    label: 'Twilight definition',
    description: 'Which twilight threshold counts as "night" for sequence start/end and observation-window calculations.',
    keywords: ['twilight', 'civil', 'nautical', 'astronomical', 'dusk', 'dawn', 'sun', 'night'],
    path: ['Settings', 'Safety', 'Site'],
    type: SettingType.enumValue(['Civil (−6°)', 'Nautical (−12°)', 'Astronomical (−18°)']),
    defaultValue: 'Astronomical (−18°)',
    profilePath: 'site.twilight_definition',
  ),

  // §29.2 File naming options that don't overlap with the storage panel.
  // State lives in `filenamesSettingsProvider`. File format / compression /
  // filename template themselves live in StorageSettings (see registry above).
  Setting(
    id: 'session.filenames.date_separator',
    label: 'Date separator',
    description: 'How `\$\$DATE*\$\$` tokens render: `/` produces real subdirectories per date; `_` and `-` keep dates inline in flat filenames.',
    keywords: ['date', 'separator', 'directory', 'slash', 'underscore', 'dash', 'flat', 'windows'],
    path: ['Settings', 'Session', 'Filenames'],
    type: SettingType.enumValue(['/  (forward slash)', '_  (underscore)', '-  (dash)']),
    defaultValue: '/  (forward slash)',
    profilePath: 'filenames.date_separator',
  ),
  Setting(
    id: 'session.filenames.compress_darks_and_bias',
    label: 'Compress bias/dark frames',
    description: 'Apply RICE compression to bias + dark calibration frames regardless of the main compression setting. They compress losslessly very well.',
    keywords: ['compress', 'dark', 'bias', 'calibration', 'rice', 'size'],
    path: ['Settings', 'Session', 'Filenames'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'filenames.compress_darks_and_bias',
  ),

  // §37.4 + §46.2 Filter Wheel — per-slot label list. State lives in
  // `filterWheelLabelsProvider`. Single registry entry representing the
  // whole list (vs registering 8 individual slot settings) because the
  // slots are uniform + the slot count is hardware-reported at connect
  // time. Search hits surface the whole panel; ⓘ on the section header
  // opens the help body explaining how labels feed `$$FILTER$$` tokens +
  // FITS-header values.
  Setting(
    id: 'eq.filterwheel.slot_labels',
    label: 'Filter wheel slot labels',
    description: 'Per-slot filter names. Surface in `\$\$FILTER\$\$` filename tokens, FITS-header FILTER values, sequence per-filter exposure blocks, and §29.2 calibration-set indexing.',
    keywords: ['filter', 'slot', 'label', 'wheel', 'efw', 'name', 'l', 'r', 'g', 'b', 'ha', 'oiii', 'sii'],
    path: ['Settings', 'Equipment', 'Filter Wheel'],
    type: SettingType.complex(),
    defaultValue: ['L', 'R', 'G', 'B', 'Hα', 'OIII', 'SII', ''],
    profilePath: 'filterwheel.slot_labels',
  ),

  // §52.1 connection lifecycle — per-device-type auto-connect toggles. 10
  // individual entries (vs one composite) so ⌘K "guider connect" /
  // "dome boot" / "weather auto" all resolve to the specific panel.
  // Defaults split between connect-by-default (core imaging chain) and
  // manual-connect (devices with side effects: guider starts PHD2; dome
  // moves the shutter; weather starts polling). State lives in
  // `equipmentConnectionProvider`.
  Setting(
    id: 'eq.camera.auto_connect',
    label: 'Camera auto-connect on boot',
    description: 'Connect to the camera when the daemon starts. Safe — connection only powers up the USB link, no exposure starts.',
    keywords: ['camera', 'auto-connect', 'connect', 'boot', 'startup'],
    path: ['Settings', 'Equipment', 'Camera'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'equipment.camera.auto_connect',
  ),
  Setting(
    id: 'eq.mount.auto_connect',
    label: 'Mount auto-connect on boot',
    description: 'Connect to the mount when the daemon starts. Sidereal tracking comes on per §57 mount-safety policy.',
    keywords: ['mount', 'telescope', 'auto-connect', 'connect', 'boot', 'startup'],
    path: ['Settings', 'Equipment', 'Mount'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'equipment.mount.auto_connect',
  ),
  Setting(
    id: 'eq.focuser.auto_connect',
    label: 'Focuser auto-connect on boot',
    description: 'Connect to the focuser when the daemon starts. Position is read on connect; no movement triggered.',
    keywords: ['focuser', 'focus', 'auto-connect', 'connect', 'boot', 'startup'],
    path: ['Settings', 'Equipment', 'Focuser'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'equipment.focuser.auto_connect',
  ),
  Setting(
    id: 'eq.filterwheel.auto_connect',
    label: 'Filter wheel auto-connect on boot',
    description: 'Connect to the filter wheel when the daemon starts. Moves to last-known slot on connect.',
    keywords: ['filter wheel', 'efw', 'auto-connect', 'connect', 'boot', 'startup'],
    path: ['Settings', 'Equipment', 'Filter Wheel'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'equipment.filterwheel.auto_connect',
  ),
  Setting(
    id: 'eq.rotator.auto_connect',
    label: 'Rotator auto-connect on boot',
    description: 'Connect to the rotator when the daemon starts. Position is read on connect; no movement triggered.',
    keywords: ['rotator', 'auto-connect', 'connect', 'boot', 'startup'],
    path: ['Settings', 'Equipment', 'Rotator'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'equipment.rotator.auto_connect',
  ),
  Setting(
    id: 'eq.guider.auto_connect',
    label: 'Guider auto-connect on boot',
    description: 'Connect to the guider (PHD2 / openastro-phd2) when the daemon starts. Starts the PHD2 client process — defaults off because some users prefer manual PHD2 launch.',
    keywords: ['guider', 'phd2', 'guide', 'auto-connect', 'connect', 'boot', 'startup'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.bool(),
    defaultValue: false,
    profilePath: 'equipment.guider.auto_connect',
  ),
  Setting(
    id: 'eq.flat.auto_connect',
    label: 'Flat panel auto-connect on boot',
    description: 'Connect to the flat-panel device (Alpaca CoverCalibrator) when the daemon starts. Connection alone doesn\'t change cover position.',
    keywords: ['flat', 'panel', 'covercalibrator', 'auto-connect', 'connect', 'boot', 'startup'],
    path: ['Settings', 'Equipment', 'Flat Panel'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'equipment.flat.auto_connect',
  ),
  Setting(
    id: 'eq.dome.auto_connect',
    label: 'Dome auto-connect on boot',
    description: 'Connect to the dome when the daemon starts. Defaults off — some dome drivers move the shutter or rotate to home on connect.',
    keywords: ['dome', 'shutter', 'auto-connect', 'connect', 'boot', 'startup'],
    path: ['Settings', 'Equipment', 'Dome'],
    type: SettingType.bool(),
    defaultValue: false,
    profilePath: 'equipment.dome.auto_connect',
  ),
  Setting(
    id: 'eq.weather.auto_connect',
    label: 'Weather auto-connect on boot',
    description: 'Connect to the weather station when the daemon starts. Defaults off — keeps the polling loop quiet until you actively want safety-monitor data.',
    keywords: ['weather', 'auto-connect', 'connect', 'boot', 'startup', 'polling'],
    path: ['Settings', 'Equipment', 'Weather'],
    type: SettingType.bool(),
    defaultValue: false,
    profilePath: 'equipment.weather.auto_connect',
  ),
  Setting(
    id: 'eq.safety.auto_connect',
    label: 'Safety monitor auto-connect on boot',
    description: 'Connect to the safety monitor when the daemon starts. Recommended on for unattended observatories.',
    keywords: ['safety', 'monitor', 'auto-connect', 'connect', 'boot', 'startup'],
    path: ['Settings', 'Equipment', 'Safety Monitor'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'equipment.safety.auto_connect',
  ),

  // §37.11 Autofocus — 12 fields covering method + V-curve params + triggers
  // + failure handling. State lives in `autofocusSettingsProvider`.
  Setting(
    id: 'img.autofocus.method',
    label: 'Autofocus method',
    description: 'Algorithm used to find best-focus position. HFR V-curve is the default for most CMOS cameras.',
    keywords: ['method', 'algorithm', 'hfr', 'fwhm', 'v-curve', 'brightest star', 'focus'],
    path: ['Settings', 'Imaging', 'Autofocus'],
    type: SettingType.enumValue(['HFR V-curve', 'Brightest-star HFR', 'FWHM (Gaussian fit)']),
    defaultValue: 'HFR V-curve',
    profilePath: 'autofocus.method',
  ),
  Setting(
    id: 'img.autofocus.steps',
    label: 'Number of steps',
    description: 'How many focuser positions to sample around the current position. More steps = more accurate fit but slower runs.',
    keywords: ['steps', 'samples', 'positions', 'count', 'focus'],
    path: ['Settings', 'Imaging', 'Autofocus'],
    type: SettingType.intRange(min: 3, max: 31),
    defaultValue: 7,
    profilePath: 'autofocus.steps',
  ),
  Setting(
    id: 'img.autofocus.step_size',
    label: 'Step size (focuser steps)',
    description: 'Distance between sample positions, in focuser native steps. Should span ~3-5x the critical focus zone.',
    keywords: ['step size', 'distance', 'increment', 'focuser', 'cfz'],
    path: ['Settings', 'Imaging', 'Autofocus'],
    type: SettingType.intRange(min: 1, max: 1000),
    defaultValue: 50,
    profilePath: 'autofocus.step_size',
  ),
  Setting(
    id: 'img.autofocus.exposure_seconds',
    label: 'Exposure time (s)',
    description: 'Per-sample exposure duration. 3-10s typical — long enough for clean HFR but short enough to keep the AF run under a couple of minutes.',
    keywords: ['exposure', 'time', 'seconds', 'duration', 'focus'],
    path: ['Settings', 'Imaging', 'Autofocus'],
    type: SettingType.intRange(min: 1, max: 60),
    defaultValue: 5,
    profilePath: 'autofocus.exposure_seconds',
  ),
  Setting(
    id: 'img.autofocus.binning',
    label: 'Binning',
    description: 'Pixel binning during AF exposures. 1 = native; 2 = 2x2 for faster star detection on long-focal-length setups.',
    keywords: ['binning', 'bin', 'resolution', 'focus'],
    path: ['Settings', 'Imaging', 'Autofocus'],
    type: SettingType.intRange(min: 1, max: 4),
    defaultValue: 1,
    profilePath: 'autofocus.binning',
  ),
  Setting(
    id: 'img.autofocus.af_filter',
    label: 'AF filter',
    description: 'Which filter to use during AF runs. L (luminance) is typical for mono setups — brightest signal, fastest convergence.',
    keywords: ['filter', 'af', 'luminance', 'l', 'focus'],
    path: ['Settings', 'Imaging', 'Autofocus'],
    type: SettingType.string(),
    defaultValue: 'L',
    profilePath: 'autofocus.af_filter',
  ),
  Setting(
    id: 'img.autofocus.run_after_filter_change',
    label: 'Run AF after filter change',
    description: 'Trigger an AF run automatically when the sequence changes filters. Compensates for filter-thickness focus offsets.',
    keywords: ['filter change', 'trigger', 'auto', 'offset', 'focus'],
    path: ['Settings', 'Imaging', 'Autofocus'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'autofocus.run_after_filter_change',
  ),
  Setting(
    id: 'img.autofocus.trigger_temp_delta_c',
    label: 'Trigger temp delta (°C)',
    description: 'Run AF when the focuser temperature has drifted by this many °C since the last run. Compensates for thermal expansion of the focuser tube.',
    keywords: ['temperature', 'delta', 'trigger', 'thermal', 'drift', 'focus'],
    path: ['Settings', 'Imaging', 'Autofocus'],
    type: SettingType.doubleRange(min: 0, max: 10, step: 0.1),
    defaultValue: 2.0,
    profilePath: 'autofocus.trigger_temp_delta_c',
  ),
  Setting(
    id: 'img.autofocus.trigger_hfr_drift_pct',
    label: 'Trigger HFR drift threshold (%)',
    description: 'Run AF when the median HFR of recent frames has worsened by this percentage. Catches focus drift between scheduled AF runs.',
    keywords: ['hfr', 'drift', 'trigger', 'percent', 'focus', 'quality'],
    path: ['Settings', 'Imaging', 'Autofocus'],
    type: SettingType.doubleRange(min: 0, max: 100, step: 1),
    defaultValue: 15.0,
    profilePath: 'autofocus.trigger_hfr_drift_pct',
  ),
  Setting(
    id: 'img.autofocus.every_n_hours',
    label: 'Every N hours (0 = off)',
    description: 'Force an AF run every N hours regardless of temp/HFR triggers. 0 disables the time-based trigger.',
    keywords: ['hours', 'interval', 'periodic', 'time', 'trigger', 'focus'],
    path: ['Settings', 'Imaging', 'Autofocus'],
    type: SettingType.intRange(min: 0, max: 12),
    defaultValue: 2,
    profilePath: 'autofocus.every_n_hours',
  ),
  Setting(
    id: 'img.autofocus.abort_sequence_on_af_failure',
    label: 'Abort sequence if AF fails',
    description: 'When AF can\'t converge, abort the running sequence. Conservative default — bad focus wastes the night.',
    keywords: ['abort', 'sequence', 'failure', 'fail', 'focus'],
    path: ['Settings', 'Imaging', 'Autofocus'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'autofocus.abort_sequence_on_af_failure',
  ),
  Setting(
    id: 'img.autofocus.restore_position_on_failure',
    label: 'Restore position on failure',
    description: 'On AF failure, return the focuser to the pre-AF position instead of stopping wherever it ended up.',
    keywords: ['restore', 'position', 'failure', 'rollback', 'focus'],
    path: ['Settings', 'Imaging', 'Autofocus'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'autofocus.restore_position_on_failure',
  ),

  // §37.10 Plate Solving — 11 fields covering solver + parameters + slew/sync.
  // State lives in `plateSolveSettingsProvider`.
  Setting(
    id: 'img.platesolve.engine',
    label: 'Solver engine',
    description: 'Plate-solving algorithm. ASTAP is fast + bundled; astrometry.net is the gold-standard online or via local index; PlateSolve 2 is the legacy Windows option.',
    keywords: ['engine', 'astap', 'astrometry.net', 'platesolve2', 'solver'],
    path: ['Settings', 'Imaging', 'Plate Solving'],
    type: SettingType.enumValue(['ASTAP', 'astrometry.net', 'PlateSolve 2']),
    defaultValue: 'ASTAP',
    profilePath: 'platesolve.engine',
  ),
  Setting(
    id: 'img.platesolve.path_or_endpoint',
    label: 'Path / endpoint',
    description: 'Local executable path for ASTAP/PlateSolve2 or HTTP endpoint for astrometry.net. Default `/usr/bin/astap` for Debian/RPi.',
    keywords: ['path', 'endpoint', 'executable', 'url', 'solver'],
    path: ['Settings', 'Imaging', 'Plate Solving'],
    type: SettingType.path(),
    defaultValue: '/usr/bin/astap',
    profilePath: 'platesolve.path_or_endpoint',
  ),
  Setting(
    id: 'img.platesolve.index_download_path',
    label: 'Index download path',
    description: 'Where ASTAP star-index databases are stored. Defaults to `/var/lib/astap` (the Debian package install path).',
    keywords: ['index', 'download', 'database', 'stars', 'catalog', 'path'],
    path: ['Settings', 'Imaging', 'Plate Solving'],
    type: SettingType.path(),
    defaultValue: '/var/lib/astap',
    profilePath: 'platesolve.index_download_path',
  ),
  Setting(
    id: 'img.platesolve.search_radius_deg',
    label: 'Search radius (°)',
    description: 'How far from the hinted position to search for a solution. Smaller = faster but risk of failure if hint is off.',
    keywords: ['search', 'radius', 'degrees', 'hint', 'blind'],
    path: ['Settings', 'Imaging', 'Plate Solving'],
    type: SettingType.doubleRange(min: 0, max: 180, step: 1),
    defaultValue: 30.0,
    profilePath: 'platesolve.search_radius_deg',
  ),
  Setting(
    id: 'img.platesolve.downsample_factor',
    label: 'Downsample factor',
    description: 'Pixel downsampling before solve. 2 = halve resolution → ~4x faster solve with negligible accuracy hit on most setups.',
    keywords: ['downsample', 'factor', 'resolution', 'speed'],
    path: ['Settings', 'Imaging', 'Plate Solving'],
    type: SettingType.intRange(min: 1, max: 8),
    defaultValue: 2,
    profilePath: 'platesolve.downsample_factor',
  ),
  Setting(
    id: 'img.platesolve.timeout_seconds',
    label: 'Timeout (s)',
    description: 'How long to wait for a single solve attempt before giving up. 60s is generous for ASTAP local; bump for astrometry.net online.',
    keywords: ['timeout', 'seconds', 'wait', 'limit'],
    path: ['Settings', 'Imaging', 'Plate Solving'],
    type: SettingType.intRange(min: 5, max: 600),
    defaultValue: 60,
    profilePath: 'platesolve.timeout_seconds',
  ),
  Setting(
    id: 'img.platesolve.use_blind_fallback',
    label: 'Use blind solve as fallback',
    description: 'If a hint-based solve times out, retry with no hint (search the whole sky). Slower but rescues bad mount alignment.',
    keywords: ['blind', 'fallback', 'retry', 'alignment'],
    path: ['Settings', 'Imaging', 'Plate Solving'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'platesolve.use_blind_fallback',
  ),
  Setting(
    id: 'img.platesolve.center_after_slew',
    label: 'Center target after slew',
    description: 'After a slew, plate-solve and re-slew until the target is within the convergence tolerance. Compensates for mount pointing error.',
    keywords: ['center', 'slew', 'pointing', 'recenter', 'goto'],
    path: ['Settings', 'Imaging', 'Plate Solving'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'platesolve.center_after_slew',
  ),
  Setting(
    id: 'img.platesolve.sync_to_coordinates',
    label: 'Sync mount to solved coords',
    description: 'Push the solved coordinates back to the mount as a sync, improving pointing accuracy for subsequent slews.',
    keywords: ['sync', 'mount', 'coordinates', 'pointing', 'alignment'],
    path: ['Settings', 'Imaging', 'Plate Solving'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'platesolve.sync_to_coordinates',
  ),
  Setting(
    id: 'img.platesolve.max_iterations',
    label: 'Max iterations',
    description: 'Maximum number of center-after-slew iterations before giving up. Each iteration solves + slews to refine pointing.',
    keywords: ['iterations', 'max', 'centering', 'refine'],
    path: ['Settings', 'Imaging', 'Plate Solving'],
    type: SettingType.intRange(min: 1, max: 20),
    defaultValue: 5,
    profilePath: 'platesolve.max_iterations',
  ),
  Setting(
    id: 'img.platesolve.convergence_tolerance_arcsec',
    label: 'Convergence tolerance (″)',
    description: 'Center-after-slew stops once the target is within this many arcseconds of the requested center. Lower = more iterations.',
    keywords: ['convergence', 'tolerance', 'arcsec', 'precision', 'centering'],
    path: ['Settings', 'Imaging', 'Plate Solving'],
    type: SettingType.doubleRange(min: 1, max: 600, step: 1),
    defaultValue: 60.0,
    profilePath: 'platesolve.convergence_tolerance_arcsec',
  ),

  // §63 PHD2 / guider — 10 fields covering connection + dithering + calibration.
  // State lives in `phd2SettingsProvider`. The §35 meridian-flip re-cal guider
  // policy lives in `safetyPoliciesProvider` (already registered) since it's
  // a meridian-flip behaviour, not a PHD2-internal one.
  Setting(
    id: 'eq.guider.host',
    label: 'PHD2 host',
    description: 'Hostname or IP where PHD2 (or openastro-phd2) is running. Default `localhost` for same-machine setups; use the daemon\'s LAN IP for remote PHD2.',
    keywords: ['phd2', 'host', 'hostname', 'ip', 'guider', 'remote'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.string(),
    defaultValue: 'localhost',
    profilePath: 'phd2.host',
  ),
  Setting(
    id: 'eq.guider.port',
    label: 'PHD2 port',
    description: 'TCP port for the PHD2 server-mode socket. 4400 is the standard default; rebind only if PHD2 is configured non-standard.',
    keywords: ['phd2', 'port', 'tcp', 'guider', 'network'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.intRange(min: 1024, max: 65535),
    defaultValue: 4400,
    profilePath: 'phd2.port',
  ),
  Setting(
    id: 'eq.guider.profile',
    label: 'PHD2 profile',
    description: 'Which PHD2 equipment profile to use. PHD2 stores per-mount/camera profiles separate from ARA\'s profiles.',
    keywords: ['phd2', 'profile', 'equipment', 'guider'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.string(),
    defaultValue: 'Default',
    profilePath: 'phd2.profile',
  ),
  Setting(
    id: 'eq.guider.dither_enabled',
    label: 'Enable dithering',
    description: 'Shift the mount by a few pixels between exposures so fixed-pattern noise (hot pixels, walking noise) randomizes across the stack.',
    keywords: ['dither', 'enable', 'guider', 'phd2', 'hot pixel', 'walking noise'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.bool(),
    defaultValue: true,
    profilePath: 'phd2.dither_enabled',
  ),
  Setting(
    id: 'eq.guider.dither_every_n_frames',
    label: 'Dither every N frames',
    description: 'How often to dither. 1 = every frame; 3-5 = every few frames (saves settle time on short exposures).',
    keywords: ['dither', 'interval', 'frames', 'every', 'phd2'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.intRange(min: 1, max: 100),
    defaultValue: 1,
    profilePath: 'phd2.dither_every_n_frames',
  ),
  Setting(
    id: 'eq.guider.dither_pixels',
    label: 'Dither pixels',
    description: 'How many guide-camera pixels to dither. Larger = more aggressive randomization; smaller = faster settle.',
    keywords: ['dither', 'pixels', 'amplitude', 'phd2'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.doubleRange(min: 0, max: 100, step: 0.5),
    defaultValue: 5.0,
    profilePath: 'phd2.dither_pixels',
  ),
  Setting(
    id: 'eq.guider.settle_pixels',
    label: 'Settle threshold (pixels)',
    description: 'PHD2 considers the guider settled once RMS error stays under this many pixels for `settle_time` seconds.',
    keywords: ['settle', 'threshold', 'pixels', 'rms', 'phd2', 'tolerance'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.doubleRange(min: 0, max: 10, step: 0.1),
    defaultValue: 1.5,
    profilePath: 'phd2.settle_pixels',
  ),
  Setting(
    id: 'eq.guider.settle_time_sec',
    label: 'Settle time (s)',
    description: 'How long RMS must stay under the settle threshold to count as settled.',
    keywords: ['settle', 'time', 'seconds', 'phd2', 'wait'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.intRange(min: 0, max: 120),
    defaultValue: 10,
    profilePath: 'phd2.settle_time_sec',
  ),
  Setting(
    id: 'eq.guider.settle_timeout_sec',
    label: 'Settle timeout (s)',
    description: 'Give up waiting for settle after this many seconds. Resumes the exposure even if RMS is still high.',
    keywords: ['settle', 'timeout', 'seconds', 'phd2', 'limit'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.intRange(min: 1, max: 600),
    defaultValue: 60,
    profilePath: 'phd2.settle_timeout_sec',
  ),
  Setting(
    id: 'eq.guider.force_calibration_each_session',
    label: 'Force calibration each session',
    description: 'Re-run PHD2 calibration at every session start instead of reusing the previous calibration. Slower but safer for setups where guide-scope orientation may have shifted.',
    keywords: ['calibration', 'force', 'session', 'phd2', 'recalibrate'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.bool(),
    defaultValue: false,
    profilePath: 'phd2.force_calibration_each_session',
  ),
  // §63.5 guider-engine config — pushed to the guider daemon on connect.
  Setting(
    id: 'eq.guider.guide_focal_length',
    label: 'Guide focal length (mm)',
    description: 'Focal length of the guide scope, pushed to PHD2 on connect. With the guide pixel size it sets the guider arcsec/pixel scale. 0 leaves the PHD2 profile default.',
    keywords: ['guide', 'focal', 'length', 'scope', 'phd2', 'scale', 'mm'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.intRange(min: 0, max: 5000),
    defaultValue: 0,
    profilePath: 'phd2.guide_focal_length',
  ),
  Setting(
    id: 'eq.guider.guide_pixel_size',
    label: 'Guide pixel size (µm)',
    description: 'Pixel size of the guide camera, pushed to PHD2 on connect. 0 leaves the PHD2 profile default.',
    keywords: ['guide', 'pixel', 'size', 'camera', 'phd2', 'scale', 'micron'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.doubleRange(min: 0, max: 20, step: 0.1),
    defaultValue: 0.0,
    profilePath: 'phd2.guide_pixel_size',
  ),
  Setting(
    id: 'eq.guider.ra_aggressiveness',
    label: 'RA aggressiveness',
    description: 'Fraction (0–1) of each measured RA error PHD2 corrects per cycle. Lower = gentler guiding; higher = faster tracking of real drift.',
    keywords: ['ra', 'aggressiveness', 'guiding', 'phd2', 'hysteresis', 'gain'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.doubleRange(min: 0, max: 1, step: 0.05),
    defaultValue: 0.7,
    profilePath: 'phd2.ra_aggressiveness',
  ),
  Setting(
    id: 'eq.guider.dec_aggressiveness',
    label: 'Dec aggressiveness',
    description: 'Fraction (0–1) of each measured Dec error PHD2 corrects per cycle. Often run slightly lower than RA because of Dec backlash.',
    keywords: ['dec', 'declination', 'aggressiveness', 'guiding', 'phd2', 'gain'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.doubleRange(min: 0, max: 1, step: 0.05),
    defaultValue: 0.7,
    profilePath: 'phd2.dec_aggressiveness',
  ),
  Setting(
    id: 'eq.guider.minimum_move',
    label: 'Minimum move (px)',
    description: 'Smallest guide error (in pixels) PHD2 reacts to. Errors below this are ignored so the mount doesn\'t chase seeing noise.',
    keywords: ['minimum', 'move', 'min', 'guiding', 'phd2', 'noise', 'seeing'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.doubleRange(min: 0, max: 5, step: 0.05),
    defaultValue: 0.15,
    profilePath: 'phd2.minimum_move',
  ),
  Setting(
    id: 'eq.guider.dec_guide_mode',
    label: 'Dec guide mode',
    description: 'How PHD2 corrects declination: Auto (either direction), North/South only (for backlash-prone mounts), or Off (RA-only). Auto leaves PHD2\'s own setting alone.',
    keywords: ['dec', 'declination', 'guide', 'mode', 'north', 'south', 'backlash', 'phd2'],
    path: ['Settings', 'Equipment', 'Guider'],
    type: SettingType.enumValue(['Auto', 'North', 'South', 'Off']),
    defaultValue: 'Auto',
    profilePath: 'phd2.dec_guide_mode',
  ),
];
