#region "copyright"

/*
    Copyright (c) 2026 Open Astro and the OpenAstro Ara contributors

    This file is part of OpenAstro Ara (forked from N.I.N.A.).

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
*/

#endregion "copyright"

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading;
using OpenAstroAra.Core.Utility;

namespace OpenAstroAra.Astrometry {

    /// <summary>
    /// UT1-UTC (DUT1) from a snapshot of the IERS Bulletin A daily series (#1190).
    /// <para>
    /// The daemon runs offline at dark sites, so the table ships as an embedded resource
    /// (<c>External/iers-dut1.tsv</c>, regenerated by <c>scripts/update-dut1-table.py</c> before a
    /// release: about two years of observed values plus Bulletin A's year of predictions).
    /// NINA kept the same series in its SQLite database and refreshed it online at startup; the
    /// port had stubbed it to 0, which put up to 0.9 s of UT1 error (about 13 arcseconds of hour
    /// angle) into every sidereal-time and topocentric transform.
    /// </para>
    /// <para>
    /// Lookup rules, in order: inside the table, linear interpolation between the bracketing
    /// midnights (a step of 0.5 s or more between neighbours is a leap second and is held, not
    /// smeared); after the table, Bulletin A's own long-term formula
    /// <c>UT1-UTC = A + B*(MJD - M0) - (UT2-UT1)</c>, evaluated for at most
    /// <see cref="ExtrapolationDays"/> past the end and held constant beyond that (the formula is
    /// a short-range fit that knows nothing of future leap seconds); before the table, the first
    /// value. Anything outside the table also clamps to the +/-0.9 s that UTC's definition bounds
    /// DUT1 to, and logs once per process. A missing or unparseable table returns 0, which is
    /// what the stub did.
    /// </para>
    /// <para>
    /// <c>OPENASTROARA_DUT1_TABLE</c> points the daemon at a newer file without a reinstall: either
    /// the compact TSV this class writes or a raw IERS <c>finals2000A.*</c> download.
    /// </para>
    /// </summary>
    public sealed class Dut1Table {

        /// <summary>Environment variable naming a table file that overrides the embedded snapshot.</summary>
        public const string EnvOverride = "OPENASTROARA_DUT1_TABLE";

        /// <summary>Embedded-resource name of the bundled snapshot.</summary>
        public const string ResourceName = "OpenAstroAra.Astrometry.External.iers-dut1.tsv";

        /// <summary>How far past the table end the Bulletin A formula is trusted before its value is held.</summary>
        public const int ExtrapolationDays = 365;

        /// <summary>|UT1-UTC| never exceeds 0.9 s by the definition of UTC (a leap second is inserted first).</summary>
        public const double MaxAbsDut1 = 0.9;

        private static readonly Lazy<Dut1Table> bundled = new Lazy<Dut1Table>(LoadDefault, LazyThreadSafetyMode.ExecutionAndPublication);

        private readonly double[] values;
        private readonly int firstMjd;
        private readonly double extrapolationA;
        private readonly double extrapolationB;
        private readonly int extrapolationM0;
        private int loggedBefore;
        private int loggedAfter;

        private Dut1Table(int firstMjd, double[] values, string source, string bulletin, int lastObservedMjd, bool hasExtrapolation, double a, double b, int m0) {
            this.firstMjd = firstMjd;
            this.values = values;
            Source = source;
            Bulletin = bulletin;
            LastObservedMjd = lastObservedMjd;
            HasExtrapolation = hasExtrapolation;
            extrapolationA = a;
            extrapolationB = b;
            extrapolationM0 = m0;
        }

        /// <summary>The table the daemon uses: the <see cref="EnvOverride"/> file if set and readable, else the embedded snapshot.</summary>
        public static Dut1Table Bundled => bundled.Value;

        /// <summary>An empty table; every lookup returns 0.</summary>
        public static Dut1Table Empty { get; } = new Dut1Table(0, Array.Empty<double>(), "none", "none", 0, false, 0, 0, 0);

        public int Count => values.Length;
        public int FirstMjd => firstMjd;
        public int LastMjd => firstMjd + values.Length - 1;
        public DateTime FirstDate => MjdToDateTime(FirstMjd);
        public DateTime LastDate => MjdToDateTime(LastMjd);
        public int LastObservedMjd { get; }
        public DateTime LastObservedDate => MjdToDateTime(LastObservedMjd);
        public string Source { get; }
        public string Bulletin { get; }
        public bool HasExtrapolation { get; }

        /// <summary>True when <paramref name="date"/> lies inside the table (observed or predicted rows).</summary>
        public bool IsCovered(DateTime date) {
            if (values.Length == 0) {
                return false;
            }
            var mjd = DateTimeToMjd(date);
            return mjd >= FirstMjd && mjd <= LastMjd;
        }

        /// <summary>UT1-UTC in seconds at <paramref name="date"/> (any <see cref="DateTimeKind"/>; converted to UTC). Never throws.</summary>
        public double Lookup(DateTime date) {
            if (values.Length == 0) {
                return 0d;
            }

            var mjd = DateTimeToMjd(date);
            if (mjd < FirstMjd) {
                LogOnce(ref loggedBefore, $"DUT1 requested for {date.ToUniversalTime():yyyy-MM-dd} before the bundled IERS table starts ({FirstDate:yyyy-MM-dd}); holding the first value");
                return Clamp(values[0]);
            }
            if (mjd > LastMjd) {
                LogOnce(ref loggedAfter, $"DUT1 requested for {date.ToUniversalTime():yyyy-MM-dd} past the bundled IERS table ({Bulletin}, ends {LastDate:yyyy-MM-dd}); " +
                    (HasExtrapolation ? $"using the Bulletin A long-term formula for up to {ExtrapolationDays} days, then holding" : "holding the last value") +
                    " - regenerate with scripts/update-dut1-table.py or set " + EnvOverride);
                return Clamp(Extrapolate(mjd));
            }

            var lower = (int)Math.Floor(mjd);
            var index = lower - firstMjd;
            if (index >= values.Length - 1) {
                return Clamp(values[values.Length - 1]);
            }
            var v0 = values[index];
            var v1 = values[index + 1];
            if (Math.Abs(v1 - v0) >= 0.5) {
                // Leap second between the two midnights: UT1-UTC steps, it does not slope.
                return Clamp(v0);
            }
            var frac = mjd - lower;
            return Clamp(v0 + (v1 - v0) * frac);
        }

        private double Extrapolate(double mjd) {
            var last = values[values.Length - 1];
            if (!HasExtrapolation) {
                return last;
            }
            var bounded = Math.Min(mjd, LastMjd + (double)ExtrapolationDays);
            return extrapolationA + extrapolationB * (bounded - extrapolationM0) - Ut2MinusUt1(bounded);
        }

        private static double Clamp(double v) => Math.Max(-MaxAbsDut1, Math.Min(MaxAbsDut1, v));

        private static void LogOnce(ref int flag, string message) {
            if (Interlocked.Exchange(ref flag, 1) == 0) {
                Logger.Warning(message);
            }
        }

        /// <summary>
        /// Seasonal term of Bulletin A's long-term formula:
        /// UT2-UT1 = 0.022 sin(2 pi T) - 0.012 cos(2 pi T) - 0.006 sin(4 pi T) + 0.007 cos(4 pi T),
        /// T in Besselian years.
        /// </summary>
        public static double Ut2MinusUt1(double mjd) {
            var besselianYear = 1900.0 + (mjd + 2400000.5 - 2415020.31352) / 365.242198781;
            var t = 2 * Math.PI * besselianYear;
            return 0.022 * Math.Sin(t) - 0.012 * Math.Cos(t) - 0.006 * Math.Sin(2 * t) + 0.007 * Math.Cos(2 * t);
        }

        private static readonly DateTime MjdEpoch = new DateTime(1858, 11, 17, 0, 0, 0, DateTimeKind.Utc);

        public static double DateTimeToMjd(DateTime date) => (date.ToUniversalTime() - MjdEpoch).TotalDays;

        public static DateTime MjdToDateTime(double mjd) => MjdEpoch.AddDays(mjd);

        private static Dut1Table LoadDefault() {
            var overridePath = Environment.GetEnvironmentVariable(EnvOverride);
            if (!string.IsNullOrWhiteSpace(overridePath)) {
                try {
                    using var reader = new StreamReader(overridePath);
                    var table = Parse(reader, overridePath);
                    if (table.Count > 0) {
                        table.LogLoaded();
                        return table;
                    }
                    Logger.Warning($"{EnvOverride}={overridePath} holds no UT1-UTC rows; using the embedded IERS table");
                } catch (Exception ex) when (ex is IOException or UnauthorizedAccessException) {
                    Logger.Warning($"{EnvOverride}={overridePath} could not be read ({ex.Message}); using the embedded IERS table");
                }
            }

            try {
                using var stream = typeof(Dut1Table).Assembly.GetManifestResourceStream(ResourceName);
                if (stream == null) {
                    Logger.Error($"Embedded IERS DUT1 table {ResourceName} is missing; UT1-UTC falls back to 0");
                    return Empty;
                }
                using var reader = new StreamReader(stream);
                var table = Parse(reader, "embedded");
                table.LogLoaded();
                return table;
            } catch (Exception ex) when (ex is IOException or InvalidOperationException or FormatException) {
                Logger.Error($"Embedded IERS DUT1 table could not be parsed; UT1-UTC falls back to 0", ex);
                return Empty;
            }
        }

        private void LogLoaded() {
            if (Count == 0) {
                Logger.Warning($"IERS DUT1 table ({Source}) is empty; UT1-UTC falls back to 0");
                return;
            }
            var today = DateTime.UtcNow.Date;
            var summary = $"IERS DUT1 table ({Source}, {Bulletin}): {Count} days {FirstDate:yyyy-MM-dd}..{LastDate:yyyy-MM-dd}, observed through {LastObservedDate:yyyy-MM-dd}";
            if (today > LastDate) {
                Logger.Warning(summary + " - the table ended before today; UT1-UTC is extrapolated. Regenerate with scripts/update-dut1-table.py");
            } else {
                Logger.Info(summary);
            }
        }

        /// <summary>
        /// Parses either the compact <c>iers-dut1.tsv</c> layout (<c># key=value</c> headers, then
        /// <c>MJD&lt;TAB&gt;UT1-UTC&lt;TAB&gt;flag</c> rows) or raw IERS <c>finals2000A.*</c> lines. Malformed
        /// rows are skipped; missing days inside the span are filled by interpolation so lookups stay O(1).
        /// </summary>
        public static Dut1Table Parse(TextReader reader, string source = "text") {
            var rows = new SortedDictionary<int, double>();
            var bulletin = "unknown bulletin";
            var lastObserved = 0;
            var hasExtrapolation = false;
            double a = 0, b = 0;
            var m0 = 0;

            string? line;
            while ((line = reader.ReadLine()) != null) {
                if (line.Length == 0) {
                    continue;
                }
                if (line[0] == '#') {
                    var eq = line.IndexOf('=', StringComparison.Ordinal);
                    if (eq < 0) {
                        continue;
                    }
                    var key = line.Substring(1, eq - 1).Trim();
                    var value = line.Substring(eq + 1).Trim();
                    switch (key) {
                        case "bulletin":
                            bulletin = value;
                            break;
                        case "last_observed_mjd":
                            _ = int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out lastObserved);
                            break;
                        case "extrapolation_params":
                            var parts = value.Split(' ', StringSplitOptions.RemoveEmptyEntries);
                            if (parts.Length == 3
                                && double.TryParse(parts[0], NumberStyles.Float, CultureInfo.InvariantCulture, out a)
                                && double.TryParse(parts[1], NumberStyles.Float, CultureInfo.InvariantCulture, out b)
                                && int.TryParse(parts[2], NumberStyles.Integer, CultureInfo.InvariantCulture, out m0)) {
                                hasExtrapolation = true;
                            }
                            break;
                    }
                    continue;
                }

                if (TryParseCompactRow(line, out var mjd, out var dut1, out var observed)
                    || TryParseFinalsRow(line, out mjd, out dut1, out observed)) {
                    rows[mjd] = dut1;
                    if (observed && mjd > lastObserved) {
                        lastObserved = mjd;
                    }
                }
            }

            if (rows.Count == 0) {
                return new Dut1Table(0, Array.Empty<double>(), source, bulletin, 0, hasExtrapolation, a, b, m0);
            }

            var first = -1;
            var last = -1;
            foreach (var mjd in rows.Keys) {
                if (first < 0) {
                    first = mjd;
                }
                last = mjd;
            }
            var values = new double[last - first + 1];
            var previousMjd = first;
            var previousValue = rows[first];
            foreach (var kv in rows) {
                var span = kv.Key - previousMjd;
                for (var i = 1; i <= span; i++) {
                    values[previousMjd - first + i] = previousValue + (kv.Value - previousValue) * i / span;
                }
                values[kv.Key - first] = kv.Value;
                previousMjd = kv.Key;
                previousValue = kv.Value;
            }
            if (lastObserved == 0) {
                lastObserved = first;
            }
            return new Dut1Table(first, values, source, bulletin, lastObserved, hasExtrapolation, a, b, m0);
        }

        private static bool TryParseCompactRow(string line, out int mjd, out double dut1, out bool observed) {
            mjd = 0;
            dut1 = 0;
            observed = false;
            var parts = line.Split('\t');
            if (parts.Length < 2) {
                return false;
            }
            if (!int.TryParse(parts[0], NumberStyles.Integer, CultureInfo.InvariantCulture, out mjd)
                || !double.TryParse(parts[1], NumberStyles.Float, CultureInfo.InvariantCulture, out dut1)) {
                return false;
            }
            observed = parts.Length > 2 && parts[2].Trim() == "I";
            return true;
        }

        // IERS finals2000A fixed-width layout: cols 8-15 MJD, col 58 UT1-UTC flag (I/P), cols 59-68 UT1-UTC.
        private static bool TryParseFinalsRow(string line, out int mjd, out double dut1, out bool observed) {
            mjd = 0;
            dut1 = 0;
            observed = false;
            if (line.Length < 68) {
                return false;
            }
            var flag = line[57];
            if (flag != 'I' && flag != 'P') {
                return false;
            }
            if (!double.TryParse(line.AsSpan(7, 8), NumberStyles.Float, CultureInfo.InvariantCulture, out var mjdValue)
                || !double.TryParse(line.AsSpan(58, 10), NumberStyles.Float, CultureInfo.InvariantCulture, out dut1)) {
                return false;
            }
            mjd = (int)Math.Round(mjdValue);
            observed = flag == 'I';
            return true;
        }
    }
}
