#region "copyright"

/*
    Copyright (c) 2026 Open Astro and the OpenAstro Ara contributors

    This file is part of OpenAstro Ara (forked from N.I.N.A.).

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
*/

#endregion "copyright"

using System;

namespace OpenAstroAra.Server.Services;

/// <summary>
/// §45 polar alignment — the geometry ARA owns (openastro-guider design/POLAR_ALIGNMENT_DESIGN.md
/// §4: "ARA owns the routine … plate solver, state machine, refraction"): the two-point RA-axis
/// fit, the Bennett atmospheric-refraction term, and the alt/az error decomposition against the
/// APPARENT (refracted) pole at the site. Pure math — every function is deterministic and
/// unit-tested against synthetic skies (a known axis, pointings generated by Rodrigues rotation,
/// recovered exactly).
///
/// <para><b>Coordinate convention:</b> all RA/Dec are APPARENT-of-date DEGREES (precess the
/// solver's J2000 output with the Astrometry transforms before calling — precession is ~20″/yr
/// and arcmin-scale since J2000, which would otherwise swamp a sub-arcmin routine). RA is
/// degrees, never hours.</para>
/// </summary>
public static class PolarAlignGeometry {

    /// <summary>
    /// The mount's RA-axis direction from two solved pointings taken before/after a commanded RA
    /// rotation of <paramref name="rotationDeg"/> (§5 step 2 — the ASIAIR-style 2-point seed).
    /// Both pointings lie on a cone around the axis: the axis is perpendicular to their chord,
    /// in the plane spanned by their angular midpoint and their great-circle pole, with the cone
    /// half-angle fixed by <c>sin θ = |P₁P₂| / (2·sin(Δ/2))</c>. Of the two mirror solutions the
    /// one in <paramref name="northernHemisphere"/>'s celestial hemisphere is returned (a mount
    /// within tens of degrees of alignment is unambiguous).
    /// </summary>
    /// <exception cref="ArgumentOutOfRangeException">Non-finite inputs, a rotation outside
    /// (0°, 180°), coincident pointings (no axis information), or a chord longer than the
    /// rotation allows (inconsistent inputs — e.g. the mount actually slewed further than
    /// commanded, or a solve is bad).</exception>
    public static (double RaDeg, double DecDeg) FitAxisTwoPoint(
            double ra1Deg, double dec1Deg, double ra2Deg, double dec2Deg,
            double rotationDeg, bool northernHemisphere) {
        RequireFinite(ra1Deg, nameof(ra1Deg));
        RequireFinite(dec1Deg, nameof(dec1Deg));
        RequireFinite(ra2Deg, nameof(ra2Deg));
        RequireFinite(dec2Deg, nameof(dec2Deg));
        if (!(double.IsFinite(rotationDeg) && rotationDeg > 0 && rotationDeg < 180)) {
            throw new ArgumentOutOfRangeException(nameof(rotationDeg),
                "the commanded RA rotation must be in (0°, 180°) — beyond 180° the short-way chord is ambiguous");
        }

        var p1 = UnitVector(ra1Deg, dec1Deg);
        var p2 = UnitVector(ra2Deg, dec2Deg);

        var chord = Norm(Subtract(p2, p1));
        if (chord < 1e-9) {
            throw new ArgumentOutOfRangeException(nameof(ra2Deg),
                "the two pointings coincide — no axis information (did the mount actually slew?)");
        }

        // Cone half-angle from the chord + commanded rotation.
        var sinTheta = chord / (2.0 * Math.Sin(Deg2Rad(rotationDeg) / 2.0));
        if (sinTheta > 1.0 + 1e-9) {
            throw new ArgumentOutOfRangeException(nameof(rotationDeg),
                "the pointings are further apart than the commanded rotation allows — a solve is bad or the mount over-slewed");
        }
        sinTheta = Math.Min(sinTheta, 1.0);
        var cosTheta = Math.Sqrt(1.0 - sinTheta * sinTheta);

        // The axis lies in the bisector plane: span of the angular midpoint m̂ and the
        // great-circle pole ĝ = normalize(P₁×P₂). A·P₁ = cosθ and ĝ·P₁ = 0 fix the mix angle:
        // cos γ = cosθ / (m̂·P₁), where m̂·P₁ = cos(c/2) for the pointing separation c.
        var mid = Normalize(Add(p1, p2));
        var g = Normalize(Cross(p1, p2));
        var cosHalfC = Dot(mid, p1);
        var cosGamma = Math.Clamp(cosTheta / cosHalfC, -1.0, 1.0);
        var sinGamma = Math.Sqrt(1.0 - cosGamma * cosGamma);

        var a1 = Add(Scale(mid, cosGamma), Scale(g, sinGamma));
        var a2 = Add(Scale(mid, cosGamma), Scale(g, -sinGamma));

        // Disambiguate: a roughly polar-aligned mount's axis sits in the target celestial
        // hemisphere; its mirror twin is the reflection through the pointing plane.
        var poleSign = northernHemisphere ? 1.0 : -1.0;
        var axis = a1.Z * poleSign >= a2.Z * poleSign ? a1 : a2;
        return RaDec(axis);
    }

    /// <summary>
    /// Bennett's atmospheric refraction (arcminutes) at APPARENT altitude
    /// <paramref name="apparentAltDeg"/>: <c>R = cot(h + 7.31/(h + 4.4))</c>. Standard
    /// conditions (1010 hPa, 10 °C) — the classic almanac model, accurate to ~0.1′ above ~15°
    /// and adequate for the arcmin-scale term §45 requires (a "sub-arcmin" routine may not skip
    /// it: refraction at a mid-latitude pole altitude is itself around an arcminute).
    /// </summary>
    public static double BennettRefractionArcmin(double apparentAltDeg) {
        if (!(double.IsFinite(apparentAltDeg) && apparentAltDeg is >= 0 and <= 90)) {
            throw new ArgumentOutOfRangeException(nameof(apparentAltDeg),
                "apparent altitude must be in [0°, 90°]");
        }
        var argDeg = apparentAltDeg + 7.31 / (apparentAltDeg + 4.4);
        return 1.0 / Math.Tan(Deg2Rad(argDeg));
    }

    /// <summary>
    /// The alt/az adjustment from the fitted axis to the APPARENT pole — the two knob numbers.
    /// The apparent axis position (alt/az at the site for <paramref name="atUtc"/>) is compared
    /// to where a perfectly-aligned axis APPEARS: azimuth exactly at the pole (0° north / 180°
    /// south) and altitude <c>|lat| + Bennett(|lat|)</c> — solved frames see the refracted sky,
    /// so the target carries the refraction term (§45's required v1 term). Positive
    /// <c>AltErrorArcmin</c> = the axis points above the apparent pole (lower the altitude bolt);
    /// positive <c>AzErrorArcmin</c> = east of the pole (as seen facing it). The azimuth
    /// component is scaled by cos(alt) so both numbers are true arc-distances.
    /// </summary>
    public static (double AltErrorArcmin, double AzErrorArcmin) AxisError(
            double axisRaDeg, double axisDecDeg, double latitudeDeg, double longitudeDeg,
            DateTimeOffset atUtc) {
        RequireFinite(axisRaDeg, nameof(axisRaDeg));
        RequireFinite(axisDecDeg, nameof(axisDecDeg));
        if (!(double.IsFinite(latitudeDeg) && Math.Abs(latitudeDeg) is > 0 and <= 90)) {
            throw new ArgumentOutOfRangeException(nameof(latitudeDeg),
                "site latitude must be non-zero (the celestial pole sits on the horizon at the equator) and within ±90°");
        }

        var lst = TonightSkyService.LocalSiderealTimeDeg(atUtc, longitudeDeg);
        var haDeg = lst - axisRaDeg;
        var (altDeg, azDeg) = AltAz(axisDecDeg, latitudeDeg, haDeg);

        var north = latitudeDeg > 0;
        var poleAltDeg = Math.Abs(latitudeDeg);
        var apparentPoleAltDeg = poleAltDeg + BennettRefractionArcmin(poleAltDeg) / 60.0;
        var poleAzDeg = north ? 0.0 : 180.0;

        var altErrArcmin = (altDeg - apparentPoleAltDeg) * 60.0;
        // Azimuth difference wrapped to ±180°, then cos-scaled to a true arc-distance. Sign
        // convention: positive = the axis sits EAST of the pole as seen facing it (for a north
        // observer facing north, east is to the right, i.e. increasing azimuth).
        var dAz = ((azDeg - poleAzDeg + 540.0) % 360.0) - 180.0;
        var azErrArcmin = dAz * Math.Cos(Deg2Rad(altDeg)) * 60.0 * (north ? 1.0 : -1.0);
        return (altErrArcmin, azErrArcmin);
    }

    // ── spherical helpers (unit-vector algebra; RA/Dec degrees) ─────────────────────────────

    private static (double X, double Y, double Z) UnitVector(double raDeg, double decDeg) {
        var ra = Deg2Rad(raDeg);
        var dec = Deg2Rad(decDeg);
        return (Math.Cos(dec) * Math.Cos(ra), Math.Cos(dec) * Math.Sin(ra), Math.Sin(dec));
    }

    private static (double RaDeg, double DecDeg) RaDec((double X, double Y, double Z) v) {
        var ra = Math.Atan2(v.Y, v.X) * 180.0 / Math.PI;
        if (ra < 0) {
            ra += 360.0;
        }
        return (ra, Math.Asin(Math.Clamp(v.Z, -1.0, 1.0)) * 180.0 / Math.PI);
    }

    // Altitude + azimuth (azimuth from north through east, the astronomical convention) from
    // declination, site latitude, and hour angle — all degrees.
    private static (double AltDeg, double AzDeg) AltAz(double decDeg, double latDeg, double haDeg) {
        var dec = Deg2Rad(decDeg);
        var lat = Deg2Rad(latDeg);
        var ha = Deg2Rad(haDeg);
        var sinAlt = Math.Sin(dec) * Math.Sin(lat) + Math.Cos(dec) * Math.Cos(lat) * Math.Cos(ha);
        var alt = Math.Asin(Math.Clamp(sinAlt, -1.0, 1.0));
        var y = -Math.Cos(dec) * Math.Sin(ha);
        var x = Math.Sin(dec) * Math.Cos(lat) - Math.Cos(dec) * Math.Sin(lat) * Math.Cos(ha);
        var az = Math.Atan2(y, x) * 180.0 / Math.PI;
        if (az < 0) {
            az += 360.0;
        }
        return (alt * 180.0 / Math.PI, az);
    }

    private static double Deg2Rad(double deg) => deg * Math.PI / 180.0;

    private static void RequireFinite(double v, string name) {
        if (!double.IsFinite(v)) {
            throw new ArgumentOutOfRangeException(name, "must be finite");
        }
    }

    private static (double X, double Y, double Z) Add((double X, double Y, double Z) a, (double X, double Y, double Z) b)
        => (a.X + b.X, a.Y + b.Y, a.Z + b.Z);

    private static (double X, double Y, double Z) Subtract((double X, double Y, double Z) a, (double X, double Y, double Z) b)
        => (a.X - b.X, a.Y - b.Y, a.Z - b.Z);

    private static (double X, double Y, double Z) Scale((double X, double Y, double Z) a, double s)
        => (a.X * s, a.Y * s, a.Z * s);

    private static double Dot((double X, double Y, double Z) a, (double X, double Y, double Z) b)
        => a.X * b.X + a.Y * b.Y + a.Z * b.Z;

    private static (double X, double Y, double Z) Cross((double X, double Y, double Z) a, (double X, double Y, double Z) b)
        => (a.Y * b.Z - a.Z * b.Y, a.Z * b.X - a.X * b.Z, a.X * b.Y - a.Y * b.X);

    private static double Norm((double X, double Y, double Z) a) => Math.Sqrt(Dot(a, a));

    private static (double X, double Y, double Z) Normalize((double X, double Y, double Z) a)
        => Scale(a, 1.0 / Norm(a));
}
