#!/usr/bin/env python3
"""Refresh the bundled IERS UT1-UTC (DUT1) table the daemon ships (#1190).

The daemon runs offline at dark sites, so it carries a snapshot of IERS
Bulletin A's UT1-UTC series as an embedded resource
(OpenAstroAra.Astrometry/External/iers-dut1.tsv). Bulletin A publishes about a
year of daily predictions, so the snapshot goes stale roughly a year after it
was taken; past its end the daemon extends it with the bulletin's own
long-term formula (see Dut1Table.cs). Run this script before cutting a
release, commit the regenerated file, and the next .deb carries a fresh year.

    python3 scripts/update-dut1-table.py            # download + rewrite
    python3 scripts/update-dut1-table.py --since 2025-01-01
    python3 scripts/update-dut1-table.py --finals finals2000A.all --bulletin bulletinA.txt

Sources (IERS Rapid Service/Prediction Center, U.S. Naval Observatory;
"Approved for public release: distribution unlimited"):
  https://datacenter.iers.org/data/9/finals2000A.all      daily EOP series
  https://datacenter.iers.org/data/latestVersion/bulletinA.txt   weekly bulletin

finals2000A.all is fixed-width (IERS "finals2000A.all" readme):
  cols 1-2 year (2-digit), 3-4 month, 5-6 day, 8-15 MJD,
  col 58 UT1-UTC flag (I = IERS observed, P = predicted), cols 59-68 UT1-UTC [s].
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "OpenAstroAra.Astrometry" / "External" / "iers-dut1.tsv"
FINALS_URL = "https://datacenter.iers.org/data/9/finals2000A.all"
BULLETIN_URL = "https://datacenter.iers.org/data/latestVersion/bulletinA.txt"
USER_AGENT = "OpenAstroAra-dut1-updater (https://github.com/open-astro/openastro-ara)"

MJD_EPOCH = dt.date(1858, 11, 17)


def mjd_to_date(mjd: int) -> dt.date:
    return MJD_EPOCH + dt.timedelta(days=mjd)


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=60) as resp:  # noqa: S310 - fixed https URLs
        return resp.read().decode("ascii", errors="replace")


def parse_finals(text: str, since_mjd: int) -> list[tuple[int, float, str]]:
    rows: list[tuple[int, float, str]] = []
    for line in text.splitlines():
        if len(line) < 68:
            continue
        flag = line[57]
        if flag not in ("I", "P"):
            continue
        try:
            mjd = int(float(line[7:15]))
            value = float(line[58:68])
        except ValueError:
            continue
        if mjd < since_mjd:
            continue
        rows.append((mjd, value, flag))
    rows.sort()
    return rows


FORMULA_RE = re.compile(
    r"UT1-UTC\s*=\s*([-+]?\d+\.\d+)\s*([-+])\s*(\d+\.\d+)\s*\(\s*MJD\s*-\s*(\d+)\s*\)\s*-\s*\(UT2-UT1\)"
)
ISSUE_RE = re.compile(r"^\s*(\d{1,2} \w+ \d{4})\s+Vol\.\s*(\S+)\s+No\.\s*(\d+)", re.MULTILINE)


def parse_bulletin(text: str) -> tuple[str, float, float, int]:
    m = FORMULA_RE.search(text)
    if not m:
        raise SystemExit("error: could not find the UT1-UTC long-term formula in Bulletin A")
    a = float(m.group(1))
    b = float(m.group(3)) * (1 if m.group(2) == "+" else -1)
    m0 = int(m.group(4))
    issue = ISSUE_RE.search(text)
    label = f"Vol. {issue.group(2)} No. {issue.group(3)} ({issue.group(1)})" if issue else "unknown issue"
    return label, a, b, m0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--since", help="first date to keep (YYYY-MM-DD); default 1 January two years ago")
    ap.add_argument("--finals", help="local finals2000A.all instead of downloading")
    ap.add_argument("--bulletin", help="local bulletinA.txt instead of downloading")
    ap.add_argument("--output", default=str(OUTPUT))
    args = ap.parse_args()

    today = dt.date.today()
    since = dt.date.fromisoformat(args.since) if args.since else dt.date(today.year - 2, 1, 1)
    since_mjd = (since - MJD_EPOCH).days

    finals = Path(args.finals).read_text() if args.finals else fetch(FINALS_URL)
    bulletin = Path(args.bulletin).read_text() if args.bulletin else fetch(BULLETIN_URL)

    rows = parse_finals(finals, since_mjd)
    if not rows:
        raise SystemExit("error: no UT1-UTC rows parsed from finals2000A.all")
    label, a, b, m0 = parse_bulletin(bulletin)

    observed = [r for r in rows if r[2] == "I"]
    last_observed = observed[-1][0] if observed else rows[0][0]
    first, last = rows[0][0], rows[-1][0]
    if len(rows) != last - first + 1:
        raise SystemExit(f"error: table has gaps ({len(rows)} rows for MJD {first}..{last})")

    lines = [
        "# IERS Bulletin A UT1-UTC (DUT1) snapshot. Generated by scripts/update-dut1-table.py; do not edit.",
        f"# source={FINALS_URL}",
        f"# bulletin={label}",
        f"# generated={today.isoformat()}",
        f"# span={mjd_to_date(first).isoformat()}..{mjd_to_date(last).isoformat()} (MJD {first}..{last})",
        f"# last_observed_mjd={last_observed}",
        f"# extrapolation=UT1-UTC = {a:+.4f} {b:+.5f}*(MJD-{m0}) - (UT2-UT1)",
        f"# extrapolation_params={a:.4f} {b:.5f} {m0}",
        "# columns: MJD<TAB>UT1-UTC[s]<TAB>flag (I=IERS observed, P=Bulletin A prediction)",
    ]
    lines += [f"{mjd}\t{value:.7f}\t{flag}" for mjd, value, flag in rows]
    Path(args.output).write_text("\n".join(lines) + "\n")
    print(
        f"wrote {args.output}: {len(rows)} rows, {mjd_to_date(first)}..{mjd_to_date(last)}, "
        f"observed through {mjd_to_date(last_observed)}, {label}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
